-- generated by cesdk 0.1.0, do not edit
-- project: coalition 0.1

local __mods, __cache = {}, {}
local function require(name)
  local c = __cache[name]
  if c ~= nil then return c end
  local f = __mods[name]
  if not f then error("cesdk bundle: module '" .. name .. "' not found", 2) end
  local r = f()
  if r == nil then r = true end
  __cache[name] = r
  return r
end

__mods["cesdk.manifest"] = function() return { name = "coalition", version = "0.1", protocols = { "/coalition/1" } } end

__mods["main"] = function()
-- coalition - forms a fixed membership set from a clique of mutually peered servers
-- by unanimous atomic commitment, and installs it as a named object.
--
-- Each member derives the same candidate set S (its eligible connected clique,
-- capped and ordered by key) and a fingerprint fp = H(sorted S || params). Two
-- all-to-all rounds over /ces/peer/1: VOUCH (every member of S is admissible to me),
-- then CONFIRM (I hold a VOUCH from every member). A member commits when it holds a
-- VOUCH and a CONFIRM from every member over one fp. Any failed criterion,
-- mismatch, missing message, or timeout aborts the attempt, which retries after a
-- cooldown. No proposer: any member may start an attempt, and concurrent attempts
-- share a fp. Commitment requires all members to agree.
--
-- Identity is the server public key (the /ces/peer/1 counterparty key). The
-- fingerprint folds the member list and parameters, so criteria 4 to 6 reduce to a
-- fp match; criteria 1 to 3 (linked, speaking, staked) are checked locally. Reuses
-- the gossip, view, clique, and eligibility substrate. CES_MANIFEST is injected by
-- the cesdk bundler.
--
-- Each VOUCH and CONFIRM is server-signed by its origin (ces.serverSign) and relayed: a
-- vote that reaches any honest member reaches all (so a member cannot withhold from some
-- members and not others), and a relayed vote stays attributable to its origin, not the
-- relayer. Two signature-verified CONFIRMs from one origin over one fp with different
-- vhash are conclusive equivocation (vhash is a deterministic function of fp): the two
-- signed confirms are a transferable proof every node re-verifies and bans on.
--
-- A commit is provisional: a transferable proof against a member retracts it (ban and
-- reform), and a coalition is relied upon only once it has stood maturity_ms unretracted.
--
-- Shedding a member, by confidence in the evidence. Conclusive (immediate ban via
-- ces.ban_peer): equivocation and a divergent params hash, neither of which an honest
-- member can emit. Uncertain (ces.grief_peer at weight 1; the host accrues, decays, and
-- bans at a threshold): a member that vouched then withheld its confirm by the deadline
-- while still fresh, which may merely be packet loss; the withholding detector below is
-- the primary path and grief is the fast fallback. A banned peer vanishes from
-- ces.peers(), so the candidate reforms without it; safety is unaffected.

local coalition = require("coalition")
local admin     = require("admin")
local conf      = require("conf")

local SERVICE  = "coalition"
local PROTOCOL = "coalition/1"   -- bumped if the wire or criteria change (criterion 5)

local MSG_GOSSIP  = 0
local MSG_VOUCH   = 1   -- [1][origin 32][fp 32][ph 32][sig 65]
local MSG_CONFIRM = 2   -- [2][origin 32][fp 32][vhash 32][ph 32][sig 65]

-- A withheld confirm is a low-confidence signal (could be packet loss or a slow peer),
-- so report it as 1 grief and let the host's accumulate-and-decay policy decide. A
-- params divergence is conclusive (an honest member never emits a foreign params hash),
-- so it is not grief at all: report it via ces.ban_peer, an immediate ban.
local GRIEF_DEFECT = 1

-- Withholding detector: an INDIVIDUAL timeout, not a vote. For each candidate member,
-- count the confirm-rounds it entered (it vouched our fingerprint, so it owed a confirm)
-- against the rounds it actually confirmed; per-tick retransmit masks loss, so a member
-- that owed many and produced almost none is withholding, and this node drops it from its
-- own candidate. No shared reputation, no quorum: each node judges from its own first-hand
-- record (collateral-free -- an honest member sits at done==seen -- and reversible). It is
-- surgical (drops from the candidate; never peer-bans) and so cannot frame an honest node.
-- Withholding is non-transferable (absence of a confirm is not a proof), so it does not
-- propagate: a node outside the chosen clique never witnesses the withholder and keeps it.
-- Under a fixed N that residual (a withholder displacing a spare) is operator-remediable
-- (a manual ban), which is the correct place for an unprovable fault -- not a coalition vote.
local crecord = {}              -- crecord[m] = { seen = n, done = n } over the window
local WITHHOLD_MIN_SEEN = 4     -- confirm-rounds of first-hand evidence before judging
local WITHHOLD_WINDOW   = 16    -- slide: past 2x this, halve both to track recent behavior

-- ---------------------------------------------------------------------------
-- Wire helpers (big-endian, Lua-to-Lua over the mesh).
-- ---------------------------------------------------------------------------
local function put_u16(t, n) t[#t + 1] = string.char(math.floor(n / 256) % 256, n % 256) end
local function rd_u16(b, o) return b:byte(o) * 256 + b:byte(o + 1) end
-- u64 big-endian via div/mod (exact for values below 2^53, e.g. ms-since-epoch).
local function put_u64(t, n)
  local b = {}
  for i = 8, 1, -1 do b[i] = string.char(n % 256); n = math.floor(n / 256) end
  t[#t + 1] = table.concat(b)
end
local function rd_u64(b, o)
  local n = 0
  for i = 0, 7 do n = n * 256 + b:byte(o + i) end
  return n
end

-- Advertise my peer table to a peer so it can assemble the 2-hop view clique detection
-- needs. The real bound is the RUDP message size (~1 MB): an entry is 35 bytes plus the
-- address, so a full default table (max_peers 100) is a few KB, nowhere near the limit.
-- cap is a soft ceiling well above max_peers; the byte budget keeps even a large cap
-- inside one message, so the advertisement never silently drops a peer.
local GOSSIP_BUDGET = 900 * 1024
local function encode_peers(peers, cap, heard)
  local out, body, n, bytes = {}, {}, 0, 0
  for _, p in ipairs(peers) do
    if n >= cap then break end
    if p.pubkey and #p.pubkey == 32 and p.address and #p.address <= 65535 then
      local sz = 35 + #p.address
      if bytes + sz > GOSSIP_BUDGET then break end
      body[#body + 1] = p.pubkey
      body[#body + 1] = string.char(heard[p.pubkey] and 1 or 0)
      put_u16(body, #p.address)
      body[#body + 1] = p.address
      n = n + 1; bytes = bytes + sz
    end
  end
  put_u16(out, n)
  out[#out + 1] = table.concat(body)
  return table.concat(out)
end

local function decode_peers(b)
  local list = {}
  if not b or #b < 2 then return list end
  local count = rd_u16(b, 1)
  local off = 3
  for _ = 1, count do
    if off + 32 + 1 + 2 > #b + 1 then break end
    local pk = b:sub(off, off + 31); off = off + 32
    local flags = b:byte(off); off = off + 1
    local alen = rd_u16(b, off); off = off + 2
    if off + alen > #b + 1 then break end
    local addr = b:sub(off, off + alen - 1); off = off + alen
    list[#list + 1] = { pubkey = pk, address = addr, speaker = (flags % 2) == 1 }
  end
  return list
end

-- ---------------------------------------------------------------------------
-- Config.
-- ---------------------------------------------------------------------------
local cfg = conf.load("/s/coalition.conf")
local function build_opts(c)
  return {
    -- The coalition size is a single protocol constant N: exactly N nodes or nothing, not
    -- a range. Default 7 = 3f+1 at f=2 (the smallest odd Byzantine-tolerant size). It is
    -- folded into the fingerprint, so every member must run the same N; left a config only
    -- so tests can use a smaller clique.
    group_size       = conf.num(c, "group_size", 7),
    group_pow_target = conf.num(c, "group_pow_target", 500000000),
    -- Timings are deliberately relaxed: a coalition forms on a human and operator timescale
    -- (nodes come up over hours and days), so every give-up / shed / retry timer is hours,
    -- not seconds. Fast timers only cause thrash and convergence races. Tests override
    -- these to a fast clock.
    tick_ms          = conf.num(c, "tick_ms", 60000),      -- heartbeat (gossip + eval): 1 min
    gossip_cap       = conf.num(c, "gossip_cap", 512),
    stable_ticks     = conf.num(c, "stable_ticks", 3),     -- ticks a candidate must hold before an attempt
    attempt_timeout_ms = conf.num(c, "attempt_timeout_ms", 3600000),  -- give up on a stuck attempt: 1 hour
    cooldown_ms      = conf.num(c, "cooldown_ms", 600000), -- delay after an abort before the next attempt: 10 min
    member_stale_ms  = conf.num(c, "member_stale_ms", 7200000),  -- a member silent this long is gone: 2 hours
    -- A commit is PROVISIONAL: a later transferable proof against a member retracts it.
    -- A coalition is only "mature" (safe for a time-dilated consumer to build on) after it
    -- has stayed formed this long, so any proof would have propagated and surfaced first.
    maturity_ms      = conf.num(c, "maturity_ms", 604800000),   -- 1 week default

    -- Test-only: a defector vouches and gossips normally but never transmits its
    -- confirm and never commits, the withholding adversary the detector excludes.
    defect           = conf.num(c, "defect", 0) ~= 0,
    -- Test-only: an equivocator signs two contradictory confirms (same fp, different
    -- vhash) and splits them across the membership, so only relay reunites the proof.
    equivocate       = conf.num(c, "equivocate", 0) ~= 0,
    -- Test-only: a node sends its CONFIRM to exactly one member, never the rest. Relay
    -- must carry it to everyone, so the node is still included (selective withholding).
    withhold_selective = conf.num(c, "withhold_selective", 0) ~= 0,
    -- Test-only: a node forges a CONFIRM attributed to another member (origin set to a
    -- victim, signed with its OWN key) to try to frame the victim as an equivocator.
    -- serverVerify against the victim's key must reject it, so the victim is never banned.
    frameup          = conf.num(c, "frameup", 0) ~= 0,
  }
end
local opts = build_opts(cfg)

-- Parameters folded into the fingerprint. An attempt completes only among members
-- that agree on these and the protocol; disagreement yields a different fingerprint.
local function params_blob()
  return PROTOCOL .. "|" .. opts.group_size .. "|" .. opts.group_pow_target
end

local me = ces.owner_pubkey and ces.owner_pubkey() or nil

-- ---------------------------------------------------------------------------
-- State. Observed environment (from gossip) + the attempt FSM.
--   state: "idle" | "collecting" (an attempt is in flight) | "formed"
--   att  : the in-flight attempt { fp, S, S_set, vhash, vouches, confirms,
--                                  sent_confirm, deadline }
--   coal : the installed coalition { id, members, fp, formed_at }
-- ---------------------------------------------------------------------------
local view, heard, pow = {}, {}, {}
local peer_set = {}
local state = "idle"
local att = nil
local coal = nil
local cooldown_until = 0
local cand_key, cand_stable = nil, 0
local firing = false   -- re-entry guard: serverSign yields, so claim before signing

-- Observation of the relayed votes for THIS node's current canonical clique, kept even
-- when this node is outside the window. Because every vote is relayed, a withholder's
-- silence is absolute: if it confirms, the relay carries it to everyone; if it does not,
-- nobody relays anything, so every node -- including a spare outside the clique -- sees the
-- same gap and can drop the withholder on its own first-hand (relayed) record. No vote.
-- Keyed by the clique fp; reset when the clique changes. { fp, vouched, confirmed }.
local obs = { fp = nil, vouched = {}, confirmed = {} }

-- Relay dedup: a content key per distinct attestation, so each is rebroadcast once and
-- the flood dies (like gossip). seen[origin..type..fp..vhash] -> true.
local seen, seen_n = {}, 0
local function note_seen(key)
  if seen[key] then return false end
  if seen_n > 8192 then seen = {}; seen_n = 0 end
  seen[key] = true; seen_n = seen_n + 1
  return true
end

-- Equivocation memory: the vhash each origin confirmed for each fp. A second confirm
-- for the same (origin, fp) with a different vhash is conclusive equivocation (vhash is
-- a deterministic function of fp, so an honest member emits exactly one). eqv[origin..fp]
-- -> vhash. Pruned in gc_caches and capped here.
local eqv, eqv_n = {}, 0

local stat = { ticks = 0, attempts = 0, faults = 0, commits = 0, retractions = 0,
               state = "idle", members = 0, last = "init" }

local function now_ms() return math.floor(ces.now() / 1000) end
local function hex(s)
  local t = {}
  for i = 1, #s do t[i] = string.format("%02x", s:byte(i)) end
  return table.concat(t)
end

-- Fresh-heard set (liveness as a boolean set; a crashed member's heard lingers).
local function fresh_heard(now)
  local h = {}
  for k, t in pairs(heard) do
    if (now - t) <= opts.member_stale_ms then h[k] = true end
  end
  return h
end

-- fp = H(sorted S || params): roster + params + protocol in one value.
local function fingerprint(S_list)
  return ces.sha256(table.concat(S_list) .. "||" .. params_blob())
end
-- vhash = H(sorted vouchers): the CONFIRM attests which vouches the sender saw. When
-- an attempt completes the vouchers are exactly S, so every member computes the same
-- vhash; a different vhash indicates a partial or divergent vouch set.
local function vouch_hash(vouchers_set)
  local ks = {}
  for k in pairs(vouchers_set) do ks[#ks + 1] = k end
  table.sort(ks)
  return ces.sha256(table.concat(ks))
end
local function set_of(list)
  local s = {}; for _, m in ipairs(list) do s[m] = true end; return s
end
-- ph = H(params): carried alongside the fingerprint so a receiver can tell a params
-- divergence (criterion 5, a malicious or misconfigured node, grief-worthy) from a
-- mere roster divergence (two honest members transiently disagreeing on S, which is
-- not grief-worthy -- honest members share params, so their ph always matches).
local function params_hash() return ces.sha256(params_blob()) end

-- ---------------------------------------------------------------------------
-- Persistence: the installed coalition survives restart.
-- ---------------------------------------------------------------------------
local store = ces.store and ces.store("/s/coalition.kv") or nil
if store then store:create(0) end

-- The published record a consumer extension reads (see lib/coalition_read):
-- [fp 32][formed_at u64][maturity_ms u64][u16 n][members...], members ascending. The
-- record carries maturity_ms so a consumer judges maturity (now >= formed_at +
-- maturity_ms) without knowing our config. formed_at persists so the maturity clock
-- continues across a restart (a coalition that has already proven itself stays mature).
local function encode_coal(c)
  local out = {}
  out[#out + 1] = c.fp
  put_u64(out, c.formed_at or 0)
  put_u64(out, opts.maturity_ms or 0)
  put_u16(out, #c.members)
  for _, m in ipairs(c.members) do out[#out + 1] = m end
  return table.concat(out)
end
local function decode_coal(b)
  if not b or #b < 32 + 8 + 8 + 2 then return nil end
  local fp = b:sub(1, 32)
  local formed_at = rd_u64(b, 33)
  local maturity_ms = rd_u64(b, 41)
  local n = rd_u16(b, 49)
  local off = 51
  local members = {}
  for _ = 1, n do
    if off + 31 > #b then return nil end
    members[#members + 1] = b:sub(off, off + 31); off = off + 32
  end
  return { fp = fp, members = members, id = members[1], formed_at = formed_at,
           maturity_ms = maturity_ms }
end

if store then
  local c = store:get("coalition")
  if c then local d = decode_coal(c); if d then state = "formed"; coal = d end end
end

-- ---------------------------------------------------------------------------
-- Send helpers (mesh, service SERVICE). GOSSIP is link-authenticated and not
-- relayed. VOUCH and CONFIRM are server-signed by their ORIGIN and relayed, so a
-- vote that reaches any honest member reaches all (defeating selective withholding)
-- and a relayed vote stays attributable to the member, not the relayer.
-- ---------------------------------------------------------------------------
local function send_msg(to, mt, body)
  ces.peer.send(to, SERVICE, string.char(mt) .. (body or ""))
end
local function send_payload(to, payload)
  ces.peer.send(to, SERVICE, payload)
end

-- The signed scope. fp = H(S || params) already binds the roster and params; vhash is
-- the canonical H(complete vouch set) for that fp. The host (ces.serverSign) adds its
-- own reserved domain tag on top, so an attestation can never collide with another
-- server-key op. Fully specifying the scope here means two of a member's signatures
-- conflict only on a genuine disagreement over one decision, never by splicing.
local function vouch_scope(fp, ph)        return PROTOCOL .. "\1" .. fp .. ph end
local function confirm_scope(fp, vh, ph)  return PROTOCOL .. "\2" .. fp .. vh .. ph end

-- VOUCH   = [1][origin 32][fp 32][ph 32][sig 65]
-- CONFIRM = [2][origin 32][fp 32][vhash 32][ph 32][sig 65]
local function build_vouch(origin, fp, ph, sig)
  return string.char(MSG_VOUCH) .. origin .. fp .. ph .. sig
end
local function build_confirm(origin, fp, vh, ph, sig)
  return string.char(MSG_CONFIRM) .. origin .. fp .. vh .. ph .. sig
end

-- Send one of my own signed attestations to every other member of S.
local function bcast_members(S, payload)
  for _, m in ipairs(S) do if m ~= me then send_payload(m, payload) end end
end
-- Relay a received attestation to my peers, skipping the immediate sender and self.
local function relay(payload, from)
  for k in pairs(peer_set) do if k ~= me and k ~= from then send_payload(k, payload) end end
end

-- Withholding record. Called once per resolved attempt (commit or abort) that reached the
-- confirm round: for each member that vouched our fingerprint (so it owed a confirm), count
-- the round, and count it completed iff we held its confirm. Attempts that never reached the
-- confirm round blame no one. A sliding cap keeps the ratio reflecting recent behavior.
local function record_attempt()
  if not att or not att.sent_confirm then return end
  for _, m in ipairs(att.S) do
    if m ~= me and att.vouches[m] then
      local r = crecord[m]; if not r then r = { seen = 0, done = 0 }; crecord[m] = r end
      r.seen = r.seen + 1
      if att.confirms[m] then r.done = r.done + 1 end
      if r.seen >= 2 * WITHHOLD_WINDOW then
        r.seen = math.floor(r.seen / 2); r.done = math.floor(r.done / 2)
      end
    end
  end
end

-- A member with enough first-hand evidence that owed many confirms and produced almost none
-- is withholding. The cutoff is loose: honest members sit at done==seen, a withholder at
-- done==0, so any threshold strictly between separates them once loss is masked.
local function is_withholder(m)
  local r = crecord[m]
  return r ~= nil and r.seen >= WITHHOLD_MIN_SEEN and (r.done * 3) < r.seen
end

-- Drop withholders (never self) from a candidate-member list, so this node re-derives its
-- candidate without them. An individual timeout: each node acts on its own evidence.
local function drop_withholders(list)
  local out = {}
  for _, m in ipairs(list) do
    if m == me or not is_withholder(m) then out[#out + 1] = m end
  end
  return out
end

-- Observe the canonical clique this node is OUTSIDE of, via the relayed votes (obs). A
-- clique member that vouched but, while every other member confirmed, did not is the lone
-- holdout -- a withholder, by the absolute silence the relay guarantees. Record it into the
-- same crecord the in-window detector uses, so this node drops it on its own first-hand
-- record and the reform converges (the spare witnesses too). No vote, no trust in claims.
local function observe_withholders(clique, fresh)
  if not clique then return end
  for _, m in ipairs(clique) do
    if m ~= me and fresh[m] and obs.vouched[m] and not obs.confirmed[m] then
      local others_confirmed = true
      for _, x in ipairs(clique) do
        if x ~= me and x ~= m and not obs.confirmed[x] then others_confirmed = false; break end
      end
      if others_confirmed then
        local r = crecord[m]; if not r then r = { seen = 0, done = 0 }; crecord[m] = r end
        r.seen = r.seen + 1
        if r.seen >= 2 * WITHHOLD_WINDOW then
          r.seen = math.floor(r.seen / 2); r.done = math.floor(r.done / 2)
        end
      end
    end
  end
end

-- ---------------------------------------------------------------------------
-- Abort the in-flight attempt: discard its state and return to idle with a cooldown.
-- An installed coalition is left untouched, and the process is never stopped (the
-- tick and handler pcalls unwind here).
-- ---------------------------------------------------------------------------
local function abort_attempt(reason)
  if state == "collecting" then
    record_attempt()
    att = nil
    state = "idle"
    cooldown_until = now_ms() + opts.cooldown_ms
    cand_key, cand_stable = nil, 0
    stat.faults = stat.faults + 1
    stat.last = "FAULT: " .. reason
  end
end
local function fault(reason)
  abort_attempt(reason)
  error("fault")   -- unwind to the enclosing pcall
end

-- ---------------------------------------------------------------------------
-- Commit: install the coalition once a VOUCH and a CONFIRM are held from every member.
-- ---------------------------------------------------------------------------
-- Install the coalition PROVISIONALLY. It is "formed" immediately but only "mature"
-- (safe for a time-dilated consumer to build on) after maturity_ms with no retraction.
local function install()
  record_attempt()   -- a commit is a round where every member confirmed: positive samples
  coal = { fp = att.fp, members = att.S, id = att.S[1], formed_at = now_ms(),
           vouch_payload = att.vouch_payload, confirm_payload = att.confirm_payload }
  state = "formed"; att = nil
  if store then pcall(function() store:put("coalition", encode_coal(coal), 1000000) end) end
  stat.commits = stat.commits + 1
  stat.last = "formed n=" .. #coal.members .. " id=" .. hex(coal.id):sub(1, 12)
  ces.log("coalition: committed n=" .. #coal.members .. " fp=" .. hex(coal.fp):sub(1, 16))
end

-- Is m a member of the currently formed coalition?
local function coal_has(m)
  if not coal then return false end
  for _, x in ipairs(coal.members) do if x == m then return true end end
  return false
end

-- Retract a provisional coalition. A transferable proof (equivocation, params) against
-- one of its members destroys it: a Byzantine member taints the whole set. Safe because
-- nothing has been built on it yet and the consumer waits for maturity. The offender is
-- already banned by the caller; here the KV is tombstoned (so a restart does not resurrect
-- it) and the node returns to forming.
local function retract(reason)
  if state ~= "formed" then return end
  coal = nil
  state = "idle"
  cooldown_until = now_ms() + opts.cooldown_ms
  cand_key, cand_stable = nil, 0
  if store then pcall(function() store:put("coalition", "\0", 1000000) end) end
  stat.retractions = stat.retractions + 1
  stat.last = "RETRACTED: " .. reason
  ces.log("coalition: retracted (" .. reason .. ")")
end

-- A formed coalition is mature once it has stood maturity_ms without retraction.
local function coal_mature()
  return state == "formed" and coal ~= nil and (now_ms() - coal.formed_at) >= opts.maturity_ms
end

-- Rebuild my committed attestations after a restart (the KV stores only fp + members,
-- not signatures). Signs once and caches; serverSign yields, so callers are coroutines.
local function ensure_coal_payloads()
  if not coal or (coal.vouch_payload and coal.confirm_payload) then return end
  local fp, ph = coal.fp, params_hash()
  local vh = vouch_hash(set_of(coal.members))
  local sv = ces.serverSign(vouch_scope(fp, ph))
  local sc = ces.serverSign(confirm_scope(fp, vh, ph))
  if not coal or not sv or not sc then return end
  coal.vouch_payload   = build_vouch(me, fp, ph, sv)
  coal.confirm_payload = build_confirm(me, fp, vh, ph, sc)
end
-- Help a lagging member complete the committed fp by re-sending my signed attestations.
local function resend_committed(to)
  ensure_coal_payloads()
  if coal and coal.vouch_payload then send_payload(to, coal.vouch_payload) end
  if coal and coal.confirm_payload then send_payload(to, coal.confirm_payload) end
end

-- After recording a vouch or confirm: send CONFIRM once all vouches are held, and
-- commit once all confirms are held.
local function advance()
  -- A defector (test-only) vouches but never enters the confirm round: it never emits
  -- its confirm and never commits, so honest members record it as a withholder.
  if opts.defect then return end
  if not att then return end
  local n = #att.S
  local nv, nc = 0, 0
  for _ in pairs(att.vouches) do nv = nv + 1 end
  for _ in pairs(att.confirms) do nc = nc + 1 end
  if nv >= n and not att.sent_confirm then
    local fp, ph = att.fp, att.ph
    local Slist = att.S
    local vh = vouch_hash(att.vouches)
    local sig = ces.serverSign(confirm_scope(fp, vh, ph))   -- yields (host round-trip)
    local sig2, vh2
    if opts.equivocate then
      vh2 = ces.sha256(vh)                                   -- a different, canonical-looking vhash
      sig2 = ces.serverSign(confirm_scope(fp, vh2, ph))      -- yields again
    end
    -- the attempt may have been replaced or aborted during the yield(s): re-validate.
    if not sig or state ~= "collecting" or not att or att.fp ~= fp or att.sent_confirm then
      return
    end
    att.vhash = vh
    att.confirms[me] = vh
    att.sent_confirm = true
    att.confirm_payload = build_confirm(me, fp, vh, ph, sig)
    if opts.equivocate and sig2 then
      -- test-only: split the two contradictory confirms across members so only relay
      -- reunites them; honest nodes then ban via the transferable equivocation proof.
      local p2, i = build_confirm(me, fp, vh2, ph, sig2), 0
      for _, m in ipairs(Slist) do
        if m ~= me then i = i + 1; send_payload(m, (i % 2 == 0) and att.confirm_payload or p2) end
      end
    elseif opts.withhold_selective then
      -- test-only: send my confirm to exactly one member; relay must carry it to the rest.
      for _, m in ipairs(Slist) do if m ~= me then send_payload(m, att.confirm_payload); break end end
    else
      bcast_members(Slist, att.confirm_payload)
    end
    if opts.frameup then
      -- test-only: forge a CONFIRM "from" the first other member, with a different vhash,
      -- signed by ME. serverVerify against the victim's key must reject it, so the victim
      -- is never seen as an equivocator and never banned.
      local victim
      for _, m in ipairs(Slist) do if m ~= me then victim = m; break end end
      if victim then
        local fsig = ces.serverSign(confirm_scope(fp, ces.sha256(vh), ph))   -- signed by ME
        if fsig then bcast_members(Slist, build_confirm(victim, fp, ces.sha256(vh), ph, fsig)) end
      end
    end
    nc = 0; for _ in pairs(att.confirms) do nc = nc + 1 end
  end
  if att.sent_confirm and nv >= n and nc >= n then install() end
end

-- Start an attempt for candidate S by vouching the whole set.
local function fire(S)
  -- serverSign yields, so claim the state before signing: a re-entry (another vouch
  -- arriving during the yield) must not start a second concurrent attempt.
  if firing or state ~= "idle" then return end
  firing = true
  local fp = fingerprint(S)
  local ph = params_hash()
  local sig = ces.serverSign(vouch_scope(fp, ph))   -- yields (host round-trip)
  firing = false
  if not sig or state ~= "idle" then return end
  att = { fp = fp, ph = ph, S = S, S_set = set_of(S),
          vouches = { [me] = true }, confirms = {},
          sent_confirm = false, deadline = now_ms() + opts.attempt_timeout_ms,
          vouch_payload = build_vouch(me, fp, ph, sig) }
  state = "collecting"
  stat.attempts = stat.attempts + 1
  stat.last = "attempt n=" .. #S
  bcast_members(att.S, att.vouch_payload)
  advance()   -- commits immediately only in a degenerate single-member set
end

-- ---------------------------------------------------------------------------
-- Eligibility snapshot, refreshed each tick.
-- ---------------------------------------------------------------------------
local function refresh_peers()
  local peers = ces.peers() or {}
  peer_set = {}
  for _, p in ipairs(peers) do
    if p.pubkey then
      peer_set[p.pubkey] = true
      pow[p.pubkey] = p.inbound_pow or 0
    end
  end
  return peers
end

-- Does member j satisfy the local criteria (1 linked, 2 speaking, 3 staked)?
local function local_admit(j, fresh)
  return peer_set[j] and fresh[j] and (pow[j] or 0) >= opts.group_pow_target
end

-- ---------------------------------------------------------------------------
-- Inbound mesh handler. GOSSIP builds the view; VOUCH and CONFIRM drive the attempt.
-- Any deviation calls fault(), which unwinds to the pcall in listen and aborts the
-- attempt.
-- ---------------------------------------------------------------------------
local function on_msg(from, payload)
  if not payload or #payload < 1 then return end
  local mt = payload:byte(1)
  local body = payload:sub(2)

  if mt == MSG_GOSSIP then
    local first = not heard[from]
    heard[from] = now_ms()
    local list = decode_peers(body)
    local pubs = {}
    for _, e in ipairs(list) do
      pubs[#pubs + 1] = e.pubkey
      if e.speaker and not heard[e.pubkey] then heard[e.pubkey] = now_ms() end
    end
    view[from] = pubs
    if first then send_msg(from, MSG_GOSSIP, encode_peers(ces.peers() or {}, opts.gossip_cap, heard)) end
    return
  end

  if mt == MSG_VOUCH then
    -- [origin 32][fp 32][ph 32][sig 65]
    if #body < 161 then return end
    local origin = body:sub(1, 32)
    local fp     = body:sub(33, 64)
    local ph     = body:sub(65, 96)
    local sig    = body:sub(97, 161)
    if origin == me then return end
    -- Verify the origin's server signature, so a relayed (or forged) vote cannot be
    -- attributed to an honest member; only a genuinely originated vote is trusted.
    if not ces.serverVerify(origin, vouch_scope(fp, ph), sig) then return end
    if not peer_set[origin] then return end   -- not a peer of mine -> not in any clique I form
    -- Relay once (the flood dies on the seen-set), so a vote that reaches any honest
    -- member reaches all: selective withholding collapses into all-or-nothing.
    if note_seen(string.char(MSG_VOUCH) .. origin .. fp) then relay(payload, from) end
    -- Observe this vote for my canonical clique even if I am outside it (relayed silence
    -- is absolute), so I can drop a withholder on my own first-hand record.
    if fp == obs.fp then obs.vouched[origin] = true end
    if state == "formed" then
      if coal and fp == coal.fp and coal.id then resend_committed(origin) end
      return
    end
    -- Params divergence is conclusive (an honest member never signs a foreign params
    -- hash). Ban first-hand only (from == origin), so a relayed config-difference is not
    -- amplified network-wide; the offender vouches every peer directly, so each bans it.
    if from == origin and ph ~= params_hash() then
      if ces.ban_peer then ces.ban_peer(origin) end
    end
    -- Idle: a VOUCH for a fingerprint this member also derives starts its attempt.
    if state == "idle" then
      local fresh = fresh_heard(now_ms())
      local peers = ces.peers() or {}
      local mypubs = {}; for _, p in ipairs(peers) do if p.pubkey then mypubs[#mypubs + 1] = p.pubkey end end
      if me then view[me] = mypubs end
      local cand = coalition.candidate(me, drop_withholders(mypubs), view, fresh, pow, opts)
      if cand.closed and cand.members and fingerprint(cand.members) == fp
         and coalition.can_vouch(me, cand.members, peer_set, fresh, pow, opts) then
        fire(cand.members)
      end
      -- (a VOUCH that does not match is from another attempt; ignore it)
    end
    if state ~= "collecting" then return end
    if not att.S_set[origin] then return end        -- not my roster -> foreign, ignore
    if fp ~= att.fp then fault("vouch fingerprint mismatch") end
    if not local_admit(origin, fresh_heard(now_ms())) then fault("vouch from inadmissible member") end
    att.vouches[origin] = true
    advance()
    return
  end

  if mt == MSG_CONFIRM then
    -- [origin 32][fp 32][vhash 32][ph 32][sig 65]
    if #body < 193 then return end
    local origin = body:sub(1, 32)
    local fp     = body:sub(33, 64)
    local vh     = body:sub(65, 96)
    local ph     = body:sub(97, 128)
    local sig    = body:sub(129, 193)
    if origin == me then return end
    if not ces.serverVerify(origin, confirm_scope(fp, vh, ph), sig) then return end
    if not peer_set[origin] then return end
    if note_seen(string.char(MSG_CONFIRM) .. origin .. fp .. vh) then relay(payload, from) end
    -- Observe this confirm for my canonical clique even if I am outside it, so I learn who
    -- confirmed and (by the absolute silence) who withheld.
    if fp == obs.fp then obs.confirmed[origin] = true end
    -- Conclusive equivocation: a second signature-verified CONFIRM from the same origin
    -- for the same fp with a DIFFERENT vhash. vhash is a deterministic function of fp
    -- (the canonical complete vouch set), so an honest member emits exactly one; two is a
    -- transferable proof anyone re-verifies. Ban it (and fault any attempt it is in).
    local ek = origin .. fp
    local prev = eqv[ek]
    if prev ~= nil and prev ~= vh then
      if ces.ban_peer then ces.ban_peer(origin) end
      -- the proof destroys whatever the now-proven-Byzantine member is part of: a formed
      -- coalition is retracted (provisional commit, time-dilated consumer), an in-flight
      -- attempt is faulted. Either way the offender is banned and the honest set reforms.
      if state == "formed" and coal_has(origin) then
        retract("equivocation " .. hex(origin):sub(1, 8))
      elseif state == "collecting" and att and att.S_set[origin] then
        fault("equivocation " .. hex(origin):sub(1, 8))
      end
      return
    end
    if prev == nil then
      if eqv_n > 8192 then eqv = {}; eqv_n = 0 end
      eqv[ek] = vh; eqv_n = eqv_n + 1
    end
    if state == "formed" then
      if coal and fp == coal.fp and coal.id then resend_committed(origin) end
      return
    end
    if from == origin and ph ~= params_hash() then
      if ces.ban_peer then ces.ban_peer(origin) end
    end
    if state ~= "collecting" then return end
    if not att.S_set[origin] then return end
    if fp ~= att.fp then fault("confirm fingerprint mismatch") end
    if not local_admit(origin, fresh_heard(now_ms())) then fault("confirm from inadmissible member") end
    -- A CONFIRM attests the sender saw the full vouch set; its vhash must match the one
    -- over the complete roster. A mismatch here is a divergent view, not equivocation.
    if vh ~= vouch_hash(att.S_set) then fault("confirm vhash mismatch") end
    att.confirms[origin] = vh
    advance()
    return
  end
end

ces.peer.listen(SERVICE, function(from, payload)
  local ok, err = pcall(on_msg, from, payload)
  if not ok and tostring(err):find("fault") == nil then
    -- an unexpected Lua error during message handling is itself a fault
    abort_attempt("exception: " .. tostring(err))
  end
end)

-- ---------------------------------------------------------------------------
-- The tick: refresh, GC, gossip, retransmit an in-flight attempt, drive idle toward
-- an attempt, and time out a stalled attempt.
-- ---------------------------------------------------------------------------
local function gc_caches(mypubs)
  if not me then return end
  local live = { [me] = true }
  for _, k in ipairs(mypubs) do live[k] = true end
  for _, list in pairs(view) do for _, q in ipairs(list) do live[q] = true end end
  for k in pairs(view)    do if not live[k] then view[k]    = nil end end
  for k in pairs(heard)   do if not live[k] then heard[k]   = nil end end
  for k in pairs(pow)     do if not live[k] then pow[k]     = nil end end
  -- crecord (the per-member withholding tally) is keyed by member pubkey: prune departed
  -- members so it cannot grow unbounded toward the extension RLIMIT.
  for k in pairs(crecord) do if not live[k] then crecord[k] = nil end end
  -- Relay/equivocation caches are keyed by origin (eqv: origin..fp; seen: type..origin..)
  -- so prune by live membership and recount the caps.
  local en = 0
  for k in pairs(eqv)  do if not live[k:sub(1, 32)] then eqv[k] = nil else en = en + 1 end end
  eqv_n = en
  local sn = 0
  for k in pairs(seen) do if not live[k:sub(2, 33)] then seen[k] = nil else sn = sn + 1 end end
  seen_n = sn
end

local function drive(mypubs)
  local now = now_ms()

  if state == "collecting" then
    if now >= att.deadline then
      -- Defection: only once the confirm round is under way (att.sent_confirm: every
      -- member vouched our exact fingerprint), a member that vouched but never
      -- confirmed, while still fresh (so not a crash, which freshness already sheds),
      -- withheld completion. That is a low-confidence defect signal (its confirm may
      -- merely be lost), so report a small grief and let the host's accumulate-and-decay
      -- decide. A missing-vouch timeout (round never reached confirm) blames no one.
      if ces.grief_peer and att.sent_confirm then
        local fr = fresh_heard(now)
        for _, m in ipairs(att.S) do
          if m ~= me and att.vouches[m] and not att.confirms[m] and fr[m] then
            ces.grief_peer(m, GRIEF_DEFECT)
          end
        end
      end
      fault("attempt timeout")
    end
    -- A member of the in-flight set going stale (crash or partition) aborts the
    -- attempt without waiting for the timeout; a later attempt uses a fresh set.
    local fresh = fresh_heard(now)
    for _, m in ipairs(att.S) do
      if m ~= me and not fresh[m] then fault("member went stale mid-attempt") end
    end
    -- retransmit my cached signed attestations to paper over mesh loss (idempotent).
    if att.vouch_payload then bcast_members(att.S, att.vouch_payload) end
    if att.sent_confirm and att.confirm_payload then
      if opts.withhold_selective then
        -- stay selective on retransmit too, so relay is the only path to the others.
        for _, m in ipairs(att.S) do if m ~= me then send_payload(m, att.confirm_payload); break end end
      else
        bcast_members(att.S, att.confirm_payload)
      end
    end
    return
  end

  if state ~= "idle" then return end
  if now < cooldown_until then return end

  local fresh = fresh_heard(now)
  local cand = coalition.candidate(me, drop_withholders(mypubs), view, fresh, pow, opts)
  -- Track the relayed votes for my current canonical clique; reset on a clique change.
  local cfp = (cand.clique and #cand.clique > 0) and fingerprint(cand.clique) or nil
  if cfp ~= obs.fp then obs = { fp = cfp, vouched = {}, confirmed = {} } end
  -- Outside the window I cannot form, but I can still witness a withholder in the clique
  -- (relayed silence is absolute) and drop it on my own record -- so the spare converges too.
  if cand.reason == "outside-window" then observe_withholders(cand.clique, fresh) end
  if cand.closed and cand.members and coalition.can_vouch(me, cand.members, peer_set, fresh, pow, opts) then
    local key = table.concat(cand.members)
    if cand_key == key then cand_stable = cand_stable + 1
    else cand_key = key; cand_stable = 1 end
    if cand_stable >= opts.stable_ticks then
      cand_key, cand_stable = nil, 0
      fire(cand.members)
    else
      stat.last = "settling " .. cand_stable .. "/" .. opts.stable_ticks
    end
  else
    cand_key, cand_stable = nil, 0
    stat.last = cand.reason or "idle"
  end
end

local function tick()
  stat.ticks = stat.ticks + 1
  local peers = refresh_peers()
  local mypubs = {}
  for _, p in ipairs(peers) do if p.pubkey then mypubs[#mypubs + 1] = p.pubkey end end
  if me then view[me] = mypubs end
  gc_caches(mypubs)

  local frame = encode_peers(peers, opts.gossip_cap, heard)
  for _, p in ipairs(peers) do if p.pubkey then send_msg(p.pubkey, MSG_GOSSIP, frame) end end

  drive(mypubs)
  stat.state = state
  stat.members = (state == "formed") and #coal.members or 0
end

local timer
local function arm()
  if timer then ces.cancel(timer) end
  timer = ces.every(opts.tick_ms, function()
    local ok, err = pcall(tick)
    if not ok and tostring(err):find("fault") == nil then
      abort_attempt("exception: " .. tostring(err))
    end
  end)
end
arm()

admin.attach(stat, function() return state end, function() return coal end)

if ces.extension_admin then
  ces.extension_admin{
    status = function()
      local mlist = ""
      if state == "formed" then
        local hs = {}; for _, m in ipairs(coal.members) do hs[#hs + 1] = hex(m) end
        mlist = table.concat(hs, ",")
      end
      local age = (state == "formed") and (now_ms() - coal.formed_at) or 0
      return {
        state       = state,
        id          = (state == "formed") and hex(coal.id) or "",
        fp          = (state == "formed") and hex(coal.fp):sub(1, 16) or "",
        members     = tostring((state == "formed") and #coal.members or 0),
        member_list = mlist,
        -- A formed coalition is PROVISIONAL until it has stood maturity_ms unretracted;
        -- only then is it safe for a time-dilated consumer to build on.
        mature      = coal_mature() and "1" or "0",
        age_ms      = tostring(age),
        attempts      = tostring(stat.attempts),
        commits       = tostring(stat.commits),
        faults      = tostring(stat.faults),
        retractions = tostring(stat.retractions),
        ticks       = tostring(stat.ticks),
        last        = stat.last,
      }
    end,
    commands = { { id = "members", label = "List coalition members" },
                 { id = "status",  label = "One-line status" } },
    on_command = function(id, _)
      if id == "members" then
        if state ~= "formed" then return "(no coalition)" end
        local hs = {}; for _, m in ipairs(coal.members) do hs[#hs + 1] = hex(m) end
        return table.concat(hs, "\n")
      elseif id == "status" then
        return string.format("state=%s members=%d fp=%s", state,
          (coal and #coal.members or 0), (coal and hex(coal.fp):sub(1, 16) or ""))
      end
      return "unknown command: " .. tostring(id)
    end,
    config_defaults =
      "group_size = 7\n" ..
      "group_pow_target = 500000000\n" ..
      "tick_ms = 60000\n" ..
      "gossip_cap = 512\n" ..
      "stable_ticks = 3\n" ..
      "attempt_timeout_ms = 3600000\n" ..
      "cooldown_ms = 600000\n" ..
      "member_stale_ms = 7200000\n" ..
      "maturity_ms = 604800000\n",
    on_config = function(c)
      local prev = opts.tick_ms
      opts = build_opts(c)
      if opts.tick_ms ~= prev then arm() end
    end,
  }
end

ces.log("coalition: up, N=" .. opts.group_size ..
        " timeout=" .. opts.attempt_timeout_ms .. "ms state=" .. state)
ces.run()

end

__mods["coalition"] = function()
-- coalition - the pure decision core. No I/O, no mutation. Two functions:
--   candidate(): the eligible clique this node belongs to (the deterministic set S
--                every member derives identically), via a canonical clique over the
--                mutual-link graph: peel the min_n-1 core, then a greedy lexicographic
--                maximal clique. The choice depends only on the view, not on who asks.
--   can_vouch(): whether every other member satisfies the local criteria (1 to 3:
--                linked, speaking, staked), i.e. whether to vouch the whole set. The
--                remote criteria (4 to 6) collapse into a fingerprint match handled
--                in main.lua (fp = H(sorted S || params)).
-- The attempt rounds and persistence live in main.lua.

local M = {}

-- view: pubkey -> array of that node's gossiped peer pubkeys.
local function nbr_set(view, k)
  local s = {}
  local l = view[k]
  if l then for _, p in ipairs(l) do s[p] = true end end
  return s
end

-- A mutual link: u and v each gossip the other. Edges among other vertices use mutual
-- gossip, so adjacency is symmetric and read identically from the same view by every
-- node -- the derivation is a function of the view, not of which member is asking.
local function mutual(view, u, v)
  return nbr_set(view, u)[v] == true and nbr_set(view, v)[u] == true
end
M._mutual = mutual

-- The candidate-graph edge test. Edges among other vertices use mutual(); an edge
-- touching me uses my own peer list first-hand: I know my links without waiting for the
-- peer's gossip echo, so I am never spuriously peeled before my peers have re-gossiped
-- me. At convergence the echo is present and the two agree, so the derivation stays a
-- function of the agreed graph.
local function adj(view, me, u, v)
  if u == me or v == me then
    local other = (u == me) and v or u
    return nbr_set(view, me)[other] == true
  end
  return mutual(view, u, v)
end

-- Sorted ascending list of a pubkey set (raw 32-byte strings, lexicographic), so S
-- and its fingerprint are identical on every node -- the value is single-sourced
-- without a single source.
local function sorted(set)
  local out = {}
  for k in pairs(set) do out[#out + 1] = k end
  table.sort(out)
  return out
end
M._sorted = sorted

-- Formation-eligible peers: a current peer that is a confirmed coalition speaker
-- (heard, fresh) AND econ-staked (lifetime inbound PoW >= target; 0 = liveness
-- only, for tests). The only nodes we will ever coalition with.
function M.eligible(peers, heard, pow, pow_target)
  heard = heard or {}; pow = pow or {}; pow_target = pow_target or 0
  local out = {}
  for _, p in ipairs(peers) do
    if heard[p] and (pow[p] or 0) >= pow_target then out[#out + 1] = p end
  end
  return out
end

-- k-core peel: drop every vertex with fewer than k mutual links among the survivors,
-- to a fixpoint. A clique of size n needs every member at degree >= n-1, so peeling at
-- k = min_n-1 removes pendants and bridges that cannot be in any min_n clique before
-- the clique is chosen -- they are the source of greedy drag. Pure and ego-independent:
-- the same survivor set on every node from the same view.
local function kcore(verts, view, me, k)
  local live = {}
  for _, v in ipairs(verts) do live[v] = true end
  if k < 1 then return live end
  local changed = true
  while changed do
    changed = false
    for v in pairs(live) do
      local deg = 0
      for u in pairs(live) do
        if u ~= v and adj(view, me, v, u) then deg = deg + 1 end
      end
      if deg < k then live[v] = nil; changed = true end
    end
  end
  return live
end

-- candidate(me, peers, view, heard, pow, opts) -> { members, closed, reason }
-- The canonical clique this node belongs to. The size is a single protocol constant N
-- (opts.group_size): the coalition is exactly N nodes or nothing -- not a range. (A range
-- is illusory: nodes peer up slowly, so the first closed clique to settle locks in near
-- the low end and never climbs, and the size is in the fingerprint so every member must
-- agree on it regardless.) Eligible vertices (me plus my speaking, staked, linked peers)
-- are peeled to the N-1 core, then a greedy lexicographic maximal clique is taken over
-- the mutual-link graph, capped at N. A pure function of (vertices, view): with converged
-- views, heard and pow, every member derives the identical set S, regardless of which
-- member it is and of any extra non-clique peers it holds (those peel away). members is S
-- when this node is in the canonical N-clique; nil with reason "outside-window" when this
-- node falls outside the lowest-N window (a lower member leads); "too-small" when no
-- closed N-clique exists yet.
function M.candidate(me, peers, view, heard, pow, opts)
  opts = opts or {}
  local n = opts.group_size or 7
  local pow_target = opts.group_pow_target or 0

  local vset = {}
  for _, p in ipairs(M.eligible(peers, heard, pow, pow_target)) do vset[p] = true end
  vset[me] = true
  local verts = sorted(vset)

  local live = kcore(verts, view, me, n - 1)

  -- Greedy lexicographic maximal clique over the survivors: walk ascending and add each
  -- vertex linked to every vertex already chosen, stopping at N. The same walk over the
  -- same graph yields the same clique on every node.
  local clique = {}
  for _, v in ipairs(verts) do
    if live[v] then
      local ok = true
      for _, m in ipairs(clique) do
        if not adj(view, me, v, m) then ok = false; break end
      end
      if ok then
        clique[#clique + 1] = v
        if #clique >= n then break end
      end
    end
  end

  local in_clique = false
  for _, v in ipairs(clique) do if v == me then in_clique = true; break end end
  -- clique is the canonical set regardless of whether this node is in it, so an
  -- outside-window node still knows the roster (to observe its relayed votes). members is
  -- the set to act on: nil when this node is outside the window.
  if not in_clique then
    return { members = nil, clique = clique, closed = false, reason = "outside-window" }
  end
  if #clique < n then
    return { members = clique, clique = clique, closed = false, reason = "too-small" }
  end
  return { members = clique, clique = clique, closed = true, reason = "ok" }
end

-- can_vouch(me, S_list, peer_set, heard, pow, opts) -> bool
-- The local criteria: true iff every other member of S is, from this node's view,
-- linked (peer_set), a fresh speaker (heard), and staked (pow >= target): criteria 1
-- to 3. The remote criteria (4 to 6) are checked per incoming VOUCH in main.lua. A
-- node vouches the set only if all members satisfy these; otherwise it never starts.
function M.can_vouch(me, S_list, peer_set, heard, pow, opts)
  opts = opts or {}; peer_set = peer_set or {}; heard = heard or {}; pow = pow or {}
  local pow_target = opts.group_pow_target or 0
  local n = opts.group_size or 7
  if #S_list < n then return false end
  local in_S = false
  for _, s in ipairs(S_list) do if s == me then in_S = true; break end end
  if not in_S then return false end
  for _, s in ipairs(S_list) do
    if s ~= me then
      if not peer_set[s] then return false end
      if not heard[s] then return false end
      if (pow[s] or 0) < pow_target then return false end
    end
  end
  return true
end

-- The REMOTE half of the criteria (4 same roster, 5 same params, 6 vouches-all) is
-- folded into a single fingerprint match in main.lua: fp = H(sorted S || params), so
-- an incoming VOUCH whose fp equals mine agrees the exact roster, the params, and
-- vouches the whole set at once. Criteria 1-3 (linked, speaking, staked) are checked
-- locally there against the live peer table. No separate predicate is needed here.

return M

end

__mods["admin"] = function()
-- admin - observability console for the coalition extension, over the /ces/lua/1
-- relay (cesh dial <pid>). Read-only. Verbs: status (one line), members (the
-- formed coalition).

local M = {}
local Admin = {}
Admin.__index = Admin

local function hex(s)
  local t = {}
  for i = 1, #s do t[i] = string.format("%02x", s:byte(i)) end
  return table.concat(t)
end

function M.new(stat, state_fn, coal_fn)
  return setmetatable({ stat = stat, state_fn = state_fn, coal_fn = coal_fn, buf = {} },
                      Admin)
end

function Admin:cmd(conn, line)
  local c = line:match("^(%S+)")
  local state, coal, s = self.state_fn(), self.coal_fn(), self.stat
  if c == "status" then
    conn:write(string.format(
      "state=%s members=%d attempts=%d commits=%d faults=%d ticks=%d last=%s\n",
      state, (coal and #coal.members or 0), s.attempts, s.commits, s.faults, s.ticks, s.last))
  elseif c == "members" then
    if state == "formed" and coal then
      conn:write("id " .. hex(coal.id) .. "\n")
      conn:write("fp " .. hex(coal.fp) .. "\n")
      for _, m in ipairs(coal.members) do conn:write(hex(m) .. "\n") end
    else
      conn:write("(no coalition)\n")
    end
    conn:write("END\n")
  else
    conn:write("ERR unknown\n")
  end
end

function Admin:on_data(conn, data)
  local b = (self.buf[conn.id] or "") .. data
  while true do
    local line, rest = b:match("^(.-)\n(.*)$")
    if not line then break end
    b = rest
    self:cmd(conn, line)
  end
  self.buf[conn.id] = b
end

function Admin:on_close(conn) self.buf[conn.id] = nil end

function M.attach(stat, state_fn, coal_fn)
  local a = M.new(stat, state_fn, coal_fn)
  ces.conn.set_listener({
    on_data  = function(conn, data) a:on_data(conn, data) end,
    on_close = function(conn) a:on_close(conn) end,
  })
  return a
end

return M

end

__mods["conf"] = function()
-- conf - load an operator-deployed config file for an L2 extension from the file
-- store. Format: "key = value" lines; "#" starts a comment; blank and malformed
-- lines are ignored. load() returns a string->string table ({} if the file is
-- absent or file ops are unavailable, so a program always has working defaults);
-- num() and list() coerce a value. The same extension reads the same path in
-- production and under test; only the deployed file differs.

local M = {}

function M.load(path)
  local out = {}
  if not ces.file_read or not ces.file_stat then return out end
  -- READ rejects a range past EOF, so size the read to the file (stat first).
  local st = ces.file_stat(path)
  if not st or not st.size or st.size == 0 then return out end
  local n = st.size < 65536 and st.size or 65536
  local data = ces.file_read(path, 0, n)
  if not data or data == "" then return out end
  for line in (data .. "\n"):gmatch("(.-)\n") do
    local s = line:gsub("#.*$", "")
    local k, v = s:match("^%s*([%w_]+)%s*=%s*(.-)%s*$")
    if k then out[k] = v end
  end
  return out
end

-- Numeric value of key k, or default.
function M.num(t, k, default)
  local n = t[k] and tonumber(t[k])
  return n or default
end

-- Comma-separated value of key k as a list of trimmed, non-empty strings ({}).
function M.list(t, k)
  local out = {}
  if t[k] then
    for item in (t[k] .. ","):gmatch("%s*([^,]-)%s*,") do
      if item ~= "" then out[#out + 1] = item end
    end
  end
  return out
end

return M

end

CES_MANIFEST = { name = "Coalition", version = "0.1", description = "Coalition: a fixed-size clique of mutually peered servers agrees on its exact membership by leaderless, unanimous, fail-fast atomic commitment (any imperfection aborts the attempt and it reforms). The committed set is published for other extensions to build on." }
return require("main")
