-- generated by cesdk 0.1.0, do not edit
-- project: hylesolo 0.2

local __mods, __cache = {}, {}
local function require(name)
  local c = __cache[name]
  if c ~= nil then return c end
  local f = __mods[name]
  if not f then error("cesdk bundle: module '" .. name .. "' not found", 2) end
  local r = f()
  if r == nil then r = true end
  __cache[name] = r
  return r
end

__mods["cesdk.manifest"] = function() return { name = "hylesolo", version = "0.2", protocols = {  } } end

__mods["main"] = function()
-- HyleSolo - a hyle blockchain hosted inside cesluajitd, with one validator and no
-- transport: the development net. Its own program key is the sole validator, so it is its
-- own quorum and commits a block every block_pace_ms with no peers.
--
-- It implements the WHOLE hyle interface -- ops, entries, governance, sudo -- over a real
-- hyle::services::Runtime. A one-validator set just means a supermajority is one signature, so
-- a proposal executes in the block that opens it. Programs and clients written against it move
-- to a real multi-node chain unchanged.
--
-- Needs a cesluajitd built with --hyle (ces.hyle). Without it the extension still loads and
-- says so.
--
-- Talk to it: cesh dial <pid>, or any program over ces.conn. One command per line, one line
-- back, always starting `ok` or `err`.
--
--   info                      chain, height, cells, quorum, sudo_pending, supply
--   config                    the genesis economy
--   self                      the validator/program pubkey
--   height
--   mintkey                   the proof-of-work epoch key
--   account <hex32>           balance, sequence
--   entry <name>              owner, balance, timestamps, payload
--   txr <hex32>               did this tx apply, and at what height
--   submit <hex>              admit signed ops; the bytes are opaque, sign them yourself
--   faucet <amount>           mint to YOUR key (the one that bound this channel)
--
-- `submit` is the whole service: the K,V verbs (publish, update, give, delete, fund) are
-- hyle entry ops, so a client encodes and SIGNS one itself and hands it over. This program
-- never holds a user's key and never inspects the bytes.
--
-- `faucet` is the devnet's credit source. It sudo-mints to conn.pubkey -- the key CES already
-- authenticated at bind -- and that same key IS the caller's hyle account, so there is nothing
-- to look up and nothing to spoof. Per-caller cap, in RAM, reset on restart: a devnet faucet,
-- not an economy.

local cfg = {}
local running = false
local heartbeat = nil
local last_err = nil
local minted = {}       -- hex pubkey -> faucet total, this instance
local bufs = {}         -- conn id -> partial line

local height_spark = {}
local SPARK_MAX = 60

local function spark_push(h)
  height_spark[#height_spark + 1] = h
  while #height_spark > SPARK_MAX do table.remove(height_spark, 1) end
end

local function hex(s)
  if not s then return "" end
  return (s:gsub(".", function(c) return string.format("%02x", c:byte()) end))
end

local function unhex(s)
  if not s or #s == 0 or #s % 2 ~= 0 or s:find("[^0-9a-fA-F]") then return nil end
  return (s:gsub("%x%x", function(cc) return string.char(tonumber(cc, 16)) end))
end

local function num(key, def)
  return tonumber(cfg[key]) or def
end

local function has_binding()
  return ces.hyle ~= nil and ces.hyle.solo ~= nil
end

-- ---------------------------------------------------------------------------
-- Chain lifecycle
-- ---------------------------------------------------------------------------

local function do_start()
  if running then return "already running (height " .. tostring(ces.hyle.height()) .. ")" end
  if not has_binding() then return "ces.hyle absent -- build the node with --hyle" end

  local ok, err = ces.hyle.solo.start{
    chain_id     = cfg.chain_id or "hylesolo",
    alloc        = num("alloc", 1000000000),
    fee_transfer = num("fee_transfer", 10),
    fee_entry    = num("fee_entry", 10),
    fee_mint     = num("fee_mint", 1),
    fee_sudo     = num("fee_sudo", 1),
    reward_base  = num("reward_base", 2),
    rent_rate    = num("rent_rate", 1),
    rip_bounty   = num("rip_bounty", 10),
    sudo_ttl_secs = num("sudo_ttl_secs", 0),
  }
  if not ok then
    last_err = tostring(err)
    return "start failed: " .. last_err
  end

  running = true
  last_err = nil

  -- Re-arm every Start so a changed block_pace_ms actually takes effect.
  local pace = num("block_pace_ms", 1000)
  if pace < 1 then pace = 1 end
  if heartbeat then ces.cancel(heartbeat) end
  heartbeat = ces.every(pace, function()
    if running then spark_push(tonumber(ces.hyle.solo.tick()) or 0) end
  end)

  ces.log("hylesolo: started '" .. ces.hyle.chain_id() .. "', one block every " .. pace .. "ms")
  return "started '" .. ces.hyle.chain_id() .. "'"
end

local autostarted = false

-- Idempotent: whichever of the config push or the deferred fallback arrives first boots
-- the chain, and the other becomes a no-op.
local function maybe_autostart()
  if autostarted then return end
  autostarted = true
  if has_binding() and num("autostart", 1) ~= 0 then
    ces.log("hylesolo: " .. do_start())
  end
end

local function do_stop()
  if not running then return "not running" end
  running = false
  if heartbeat then ces.cancel(heartbeat); heartbeat = nil end
  ces.hyle.solo.stop()
  height_spark = {}
  minted = {}
  ces.log("hylesolo: stopped")
  return "stopped"
end

-- ---------------------------------------------------------------------------
-- The line protocol
-- ---------------------------------------------------------------------------

local cmds = {}

function cmds.info()
  local i = ces.hyle.info()
  if not i then return "err no_chain" end
  return string.format(
    "ok chain=%s height=%d accounts=%d entries=%d txs=%d mempool=%d validators=%d quorum=%d " ..
    "sudo_pending=%d sudo_minted=%d balance=%d last_block=%d self=%s app_hash=%s",
    i.chain_id, i.height, i.accounts, i.entries, i.txs, i.mempool, i.validators, i.quorum,
    i.sudo_pending, i.sudo_minted, i.balance, i.last_block_time, hex(i.self), hex(i.app_hash))
end

function cmds.config()
  local c = ces.hyle.config()
  if not c then return "err no_chain" end
  return string.format(
    "ok fee_mint=%d fee_transfer=%d fee_entry=%d fee_sudo=%d rent_rate=%d rip_bounty=%d " ..
    "sudo_ttl_secs=%d reward_base=%d",
    c.fee_mint, c.fee_transfer, c.fee_entry, c.fee_sudo, c.rent_rate, c.rip_bounty,
    c.sudo_ttl_secs, c.reward_base)
end

cmds["self"] = function()
  return "ok " .. hex(ces.hyle.self())
end

function cmds.height()
  return "ok " .. string.format("%d", ces.hyle.height())
end

function cmds.mintkey()
  local k = ces.hyle.mint_key()
  if not k then return "err no_chain" end
  return "ok " .. hex(k)
end

function cmds.account(conn, rest)
  local pk = unhex(rest:match("^(%S+)"))
  if not pk or #pk ~= 32 then return "err bad_pubkey" end
  local a = ces.hyle.account(pk)
  if not a then return "err no_chain" end
  return string.format("ok balance=%d sequence=%d exists=%d",
                       a.balance, a.sequence, a.exists and 1 or 0)
end

function cmds.entry(conn, rest)
  local name = rest:match("^(%S+)")
  if not name then return "err bad_name" end
  local e = ces.hyle.entry(name)
  if not e then return "err not_found" end
  return string.format("ok owner=%s balance=%d created=%d modified=%d rent=%d payload=%s",
                       hex(e.owner), e.balance, e.created, e.last_modified, e.last_rent,
                       hex(e.payload))
end

function cmds.txr(conn, rest)
  local id = unhex(rest:match("^(%S+)"))
  if not id or #id ~= 32 then return "err bad_txid" end
  local r = ces.hyle.tx_result(id)
  if not r then return "err not_found" end
  return string.format("ok height=%d applied=%d", r.height, r.applied and 1 or 0)
end

-- The carrier: opaque bytes in, tx ids out. We do not parse them and we could not have
-- signed them.
function cmds.submit(conn, rest)
  local raw = unhex(rest:match("^(%S+)"))
  if not raw then return "err bad_hex" end
  local ids, err = ces.hyle.submit(raw)
  if not ids then return "err " .. tostring(err) end
  local out = {}
  for _, id in ipairs(ids) do out[#out + 1] = hex(id) end
  return "ok " .. table.concat(out, " ")
end

-- Mint to the key that bound this channel. CES authenticated it; it is also, byte for byte,
-- that caller's hyle account.
function cmds.faucet(conn, rest)
  local amt = tonumber(rest:match("^(%d+)"))
  if not amt or amt <= 0 then return "err bad_amount" end
  if not conn.pubkey or #conn.pubkey ~= 32 then return "err no_caller_identity" end

  local cap = num("faucet_max", 1000000)
  local who = hex(conn.pubkey)
  local had = minted[who] or 0
  if had + amt > cap then return "err faucet_cap_reached" end

  -- Propose the mint (as the sole validator, this program is the whole quorum), then tick
  -- to commit it in this call so the caller sees it land.
  local ok, err = ces.hyle.sudo.submit(ces.hyle.sudo.op.mint{ to = conn.pubkey, amount = amt })
  if not ok then return "err " .. tostring(err) end
  ces.hyle.solo.tick()

  minted[who] = had + amt
  return string.format("ok minted=%d to=%s", amt, who)
end

local function dispatch(conn, line)
  local cmd, rest = line:match("^(%S+)%s*(.*)$")
  if not cmd then return nil end
  local h = cmds[cmd:lower()]
  if not h then return "err unknown_command" end
  if not has_binding() then return "err no_binding (build the node with --hyle)" end
  if not running and cmd:lower() ~= "self" then
    -- Carry the reason: a genesis the chain refused is the usual one, and a bare
    -- "no_chain" sends the caller looking in the wrong place.
    return "err no_chain" .. (last_err and (" " .. last_err) or "")
  end
  local ok, res = pcall(h, conn, rest or "")
  if not ok then return "err " .. tostring(res) end
  return res
end

local function serve()
  ces.conn.set_listener{
    on_open = function(conn)
      bufs[conn.id] = ""
    end,
    on_data = function(conn, data)
      local buf = (bufs[conn.id] or "") .. data
      while true do
        local i = buf:find("\n", 1, true)
        if not i then break end
        local line = (buf:sub(1, i - 1):gsub("\r$", ""))
        buf = buf:sub(i + 1)
        if #line > 0 then
          local reply = dispatch(conn, line)
          if reply then conn:write(reply .. "\n") end
        end
      end
      bufs[conn.id] = buf
    end,
    on_close = function(conn)
      bufs[conn.id] = nil
    end,
  }
end

-- ---------------------------------------------------------------------------
-- Admin panel
-- ---------------------------------------------------------------------------

local function build_panel()
  return mene.app{
    model = { last_msg = "" },
    view = function(m)
      local binding = has_binding()
      local state = not binding and "no binding" or (running and "running" or "stopped")
      local tone = running and "ok" or (binding and "warn" or "err")
      local body = {}

      if running then
        local i = ces.hyle.info()
        body[#body + 1] = mene.grid({ cols = 4, gap = 12 },
          mene.metric({ label = "height", value = string.format("%d", i.height),
                        spark = height_spark, tone = "info" }),
          mene.stat({ label = "entries", value = string.format("%d", i.entries) }),
          mene.stat({ label = "accounts", value = string.format("%d", i.accounts) }),
          mene.stat({ label = "ops in blocks", value = string.format("%d", i.txs) }))
        body[#body + 1] = mene.kv({ rows = {
          { "chain", i.chain_id },
          { "validators", string.format("%d (quorum %d)", i.validators, i.quorum) },
          { "sudo pending", string.format("%d", i.sudo_pending) },
          { "minted by sudo", string.format("%d", i.sudo_minted) },
          { "validator balance", string.format("%d", i.balance) },
          { "mempool", string.format("%d", i.mempool) },
          { "last block", string.format("%d", i.last_block_time) },
          { "app hash", hex(i.app_hash) },
        } })
      elseif not binding then
        body[#body + 1] = mene.alert({ tone = "err", title = "ces.hyle absent" },
          "build the node with --hyle to host a chain")
      else
        body[#body + 1] = mene.text({ tone = "muted" },
          "configured chain: " .. (cfg.chain_id or "hylesolo") ..
          " -- edit Config below, then Start.")
      end

      if last_err then
        body[#body + 1] = mene.alert({ tone = "err", title = "start failed" }, last_err)
      end

      body[#body + 1] = mene.stack({ gap = 4 },
        mene.text({ tone = "muted" }, "validator pubkey (this program; also its CES account)"),
        mene.text({ copy = true, tone = "code" },
          ces.program_pubkey and hex(ces.program_pubkey()) or "?"))

      body[#body + 1] = mene.row({ gap = 8 },
        mene.button({ on = "start", kind = "primary",
                      disabled = running or not binding }, "Start chain"),
        mene.button({ on = "stop", kind = "danger", disabled = not running,
                      confirm = "Stop the chain? Its state is in RAM and will be lost." },
                    "Stop chain"))

      body[#body + 1] = mene.section({ title = "genesis / economy (persists; applied on Start)" },
        mene.form({ on = "cfg" },
          mene.grid({ cols = 4, gap = 10 },
            mene.field({ name = "chain_id", label = "chain id",
                         value = cfg.chain_id or "hylesolo" }),
            mene.field({ name = "block_pace_ms", kind = "number",
                         label = "block pace ms", value = num("block_pace_ms", 1000) }),
            mene.field({ name = "alloc", kind = "number",
                         label = "genesis alloc", value = num("alloc", 1000000000) }),
            mene.field({ name = "reward_base", kind = "number",
                         label = "pow reward base", value = num("reward_base", 2) }),
            mene.field({ name = "fee_transfer", kind = "number",
                         label = "fee transfer", value = num("fee_transfer", 10) }),
            mene.field({ name = "fee_entry", kind = "number",
                         label = "fee entry", value = num("fee_entry", 10) }),
            mene.field({ name = "fee_mint", kind = "number",
                         label = "fee mint", value = num("fee_mint", 1) }),
            mene.field({ name = "fee_sudo", kind = "number",
                         label = "fee sudo", value = num("fee_sudo", 1) }),
            mene.field({ name = "rent_rate", kind = "number",
                         label = "rent per byte-second", value = num("rent_rate", 1) }),
            mene.field({ name = "rip_bounty", kind = "number",
                         label = "rip bounty", value = num("rip_bounty", 10) }),
            mene.field({ name = "sudo_ttl_secs", kind = "number",
                         label = "sudo timeout secs (0=never)", value = num("sudo_ttl_secs", 0) }),
            mene.field({ name = "faucet_max", kind = "number",
                         label = "faucet cap per caller", value = num("faucet_max", 1000000) }),
            mene.field({ name = "autostart", kind = "number",
                         label = "autostart (0/1)", value = num("autostart", 1) })),
          mene.submit({ kind = "primary" }, "Apply + save")))

      if m.last_msg ~= "" then
        body[#body + 1] = mene.text({ tone = "muted" }, m.last_msg)
      end

      return mene.card({ title = "HyleSolo",
                         subtitle = "one-validator hyle chain: the development net" },
        mene.row({ gap = 8 }, mene.badge({ tone = tone }, state)),
        unpack(body))
    end,
    update = function(ev, m)
      if ev.on == "start" then
        m.last_msg = do_start()
      elseif ev.on == "stop" then
        m.last_msg = do_stop()
      elseif ev.on == "cfg" and type(ev.value) == "table" then
        local keys = { "chain_id", "block_pace_ms", "alloc", "fee_transfer", "fee_entry",
                       "fee_mint", "fee_sudo", "reward_base", "rent_rate", "rip_bounty",
                       "sudo_ttl_secs", "faucet_max", "autostart" }
        local c, lines = {}, {}
        for _, k in ipairs(keys) do
          c[k] = tostring(ev.value[k] or "")
          lines[#lines + 1] = k .. " = " .. c[k]
        end
        cfg = c
        if ces.extension_admin.save_config then
          ces.extension_admin.save_config(table.concat(lines, "\n") .. "\n")
          m.last_msg = "config saved; applied on the next Start"
        else
          m.last_msg = "config stored for this run (host cannot persist)"
        end
      end
      return m
    end,
  }
end

-- ---------------------------------------------------------------------------

local spec = {
  status = function()
    if not running then
      return {
        state            = has_binding() and "stopped" or "no ces.hyle (needs --hyle node)",
        configured_chain = cfg.chain_id or "hylesolo",
        last_error       = last_err or "",
      }
    end
    local i = ces.hyle.info()
    return {
      state       = "running",
      chain       = i.chain_id,
      height      = string.format("%d", i.height),
      accounts    = string.format("%d", i.accounts),
      entries     = string.format("%d", i.entries),
      txs         = string.format("%d", i.txs),
      mempool     = string.format("%d", i.mempool),
      validators  = string.format("%d", i.validators),
      quorum      = string.format("%d", i.quorum),
      sudo_pending = string.format("%d", i.sudo_pending),
      sudo_minted = string.format("%d", i.sudo_minted),
      balance     = string.format("%d", i.balance),
      last_block  = string.format("%d", i.last_block_time),
      app_hash    = hex(i.app_hash),
      self        = hex(i.self),
    }
  end,

  commands = {
    { id = "start", label = "Start chain" },
    { id = "stop",  label = "Stop chain"  },
  },
  on_command = function(id)
    if id == "start" then return do_start()
    elseif id == "stop" then return do_stop() end
    return "unknown command: " .. tostring(id)
  end,

  -- Autostart cannot happen at load time: the host queues the /s/hylesolo.conf push at
  -- REGISTER and the child only dispatches it once the run loop is pumping, so starting
  -- before then boots the chain on defaults and quietly ignores the operator's genesis.
  -- Start when the config lands instead. If there is no conf file the host pushes nothing
  -- and this never fires, so a short deferred fallback below covers that case; whichever
  -- gets there first is the only one that runs.
  config_defaults = table.concat({
    "# HyleSolo: a one-validator hyle chain. This program's own key is the validator,",
    "# so it is its own quorum -- including for sudo.",
    "chain_id = hylesolo",
    "block_pace_ms = 1000",
    "# 1 = boot the chain when the extension loads",
    "autostart = 1",
    "# genesis allocation to the program's own account (whole credits)",
    "alloc = 1000000000",
    "# economy. The chain rejects a genesis where reward_base <= fee_mint, or where rent is",
    "# on and rip_bounty > min(fee_transfer, fee_entry): a bounty worth more than the fee to",
    "# create a rippable entry mints money out of the cull.",
    "fee_transfer = 10",
    "fee_entry = 10",
    "fee_mint = 1",
    "# per-op fee for a sudo propose/approve",
    "fee_sudo = 1",
    "# proof-of-work mint reward at floor difficulty",
    "reward_base = 2",
    "# rent per byte-second of entry footprint. At 0 an entry is immortal, its funding",
    "# buys nothing, and no one can ever cull it.",
    "rent_rate = 1",
    "# paid to whoever reaps a starved entry",
    "rip_bounty = 10",
    "# a pending sudo proposal past this age cannot execute and is cleared. 0 = never.",
    "sudo_ttl_secs = 0",
    "# devnet faucet: most one caller may mint, per instance",
    "faucet_max = 1000000",
    "",
  }, "\n"),
  on_config = function(c)
    cfg = c
    maybe_autostart()
  end,
}

if mene then spec.panel = build_panel() end
ces.extension_admin(spec)

ces.spawn(function()
  ces.sleep(250)
  maybe_autostart()
end)

serve()
ces.run()

end

CES_MANIFEST = { name = "HyleSolo", version = "0.2", description = "The hyle development net: a one-validator, transportless hyle-services blockchain hosted inside cesluajitd over the ces.hyle binding, with the full interface -- ops, entries, governance, sudo. Its own program key is the sole validator, so it is its own quorum and commits a block every block_pace_ms. The extension config IS the hyle genesis and economy. Serves a line protocol over ces.conn: clients sign their own ops and submit them as opaque bytes, and `faucet` sudo-mints to the key that bound the channel, which is also that caller's hyle account. Requires a cesluajitd built with --hyle." }
return require("main")
