-- generated by cesdk 0.1.0, do not edit
-- project: hylenet 0.1

local __mods, __cache = {}, {}
local function require(name)
  local c = __cache[name]
  if c ~= nil then return c end
  local f = __mods[name]
  if not f then error("cesdk bundle: module '" .. name .. "' not found", 2) end
  local r = f()
  if r == nil then r = true end
  __cache[name] = r
  return r
end

__mods["cesdk.manifest"] = function() return { name = "hylenet", version = "0.1", protocols = {  } } end

__mods["main"] = function()
-- HyleNet - a multi-node hyle blockchain hosted inside cesluajitd. The validator identity is
-- this CES SERVER's key, and consensus rides the CES server peer mesh (ces.peer.*), so the
-- validators are simply the CES servers that are mutual peers and carry the same genesis. No
-- dialing of its own: lose CES peership with a validator and BFT rides on at 2f+1.
--
-- It implements the WHOLE hyle interface -- ops, entries, governance, sudo -- over a real
-- hyle::services::Runtime, driven by a fine pump tick. The same ces.hyle.* interface as the
-- solo dev net, so programs and clients move between them unchanged.
--
-- Needs a cesluajitd built with --hyle (ces.hyle) on an ed25519 server key. Without it the
-- extension still loads and says so.
--
-- Talk to it: cesh dial <pid>, or any program over ces.conn. One command per line, one line
-- back, always starting `ok` or `err`.
--
--   info                      chain, height, cells, quorum, sudo_pending, supply
--   config                    the genesis economy
--   self                      the validator/program pubkey
--   height
--   account <hex32>           balance, sequence
--   entry <name>              owner, balance, timestamps, payload
--   txr <hex32>               did this tx apply, and at what height
--   submit <hex>              admit signed ops; the bytes are opaque, sign them yourself
--   nodekey                   (owner only) the validator private key, to load into cesh
--
-- `submit` is the whole service: the K,V verbs (publish, update, give, delete, fund) are
-- hyle entry ops, so a client encodes and SIGNS one itself and hands it over. This program
-- never holds a user's key and never inspects the bytes.
--
-- Money comes only from the validator. `nodekey` hands the node/validator private key to the
-- owner, who loads it into cesh and mints as the node (`cesh hyle <pid> mint <to> <amount>`).
-- The chain gates minting to validators, so a non-owner client cannot create money.

local cfg = {}
local running = false
local heartbeat = nil
local last_err = nil
local bufs = {}         -- conn id -> partial line

local height_spark = {}
local SPARK_MAX = 60

local function spark_push(h)
  height_spark[#height_spark + 1] = h
  while #height_spark > SPARK_MAX do table.remove(height_spark, 1) end
end

local function hex(s)
  if not s then return "" end
  return (s:gsub(".", function(c) return string.format("%02x", c:byte()) end))
end

local function unhex(s)
  if not s or #s == 0 or #s % 2 ~= 0 or s:find("[^0-9a-fA-F]") then return nil end
  return (s:gsub("%x%x", function(cc) return string.char(tonumber(cc, 16)) end))
end

local function num(key, def)
  return tonumber(cfg[key]) or def
end

local function has_binding()
  return ces.hyle ~= nil and ces.hyle.net ~= nil
end

-- Validators from config: a whitespace/comma list of 64-hex server pubkeys. Every node on the
-- chain must carry the SAME list (it is the genesis), so the operator ships one config to all.
local function parse_validators()
  local out = {}
  local s = cfg.validators
  if type(s) == "table" then
    for _, h in ipairs(s) do local b = unhex(h); if b and #b == 32 then out[#out + 1] = b end end
  elseif s then
    for h in tostring(s):gmatch("%x+") do local b = unhex(h); if b and #b == 32 then out[#out + 1] = b end end
  end
  return out
end

-- ---------------------------------------------------------------------------
-- Chain lifecycle
-- ---------------------------------------------------------------------------

local function do_start()
  if running then return "already running (height " .. tostring(ces.hyle.height()) .. ")" end
  if not has_binding() then return "ces.hyle.net absent -- build the node with --hyle" end

  local V = parse_validators()
  if #V == 0 then return "no validators configured (set validators = <hex> <hex> ...)" end

  -- The validator identity is the SERVER key (net.start reads it in-process), and consensus rides the CES
  -- server peer mesh, so this node must already be a mutual CES peer of the other validators.
  -- Funding is per-block validator autofill (through consensus), not an alloc.
  local ok, err = ces.hyle.net.start{
    chain_id     = cfg.chain_id or "hylenet",
    validators   = V,
    block_pace_ms = num("block_pace_ms", 1000),
    consensus_timeout_ms = num("consensus_timeout_ms", 1000),
    fee_transfer = num("fee_transfer", 10),
    fee_entry    = num("fee_entry", 10),
    fee_sudo     = num("fee_sudo", 1),
    rent_rate    = num("rent_rate", 1),
    rip_bounty   = num("rip_bounty", 10),
    sudo_ttl_secs = num("sudo_ttl_secs", 0),
    member_cap   = num("member_cap", 21),
    member_floor = num("member_floor", 1),
    max_state_bytes = num("max_state_bytes", 0),
    credit_autofill_ceiling = num("credit_autofill_ceiling", 0),
    refill_rate  = num("refill_rate", 0),
    block_retention   = num("block_retention", 1024),
    snapshot_interval = num("snapshot_interval", 0),
  }
  if not ok then
    last_err = tostring(err)
    return "start failed: " .. last_err
  end

  running = true
  last_err = nil

  -- Net is driven by a FINE pump tick for consensus liveness; block_pace_ms (passed to start)
  -- only throttles empty-block production. A slow spark keeps the panel sparkline cheap.
  local n = 0
  if heartbeat then ces.cancel(heartbeat) end
  heartbeat = ces.every(5, function()
    if not running then return end
    ces.hyle.net.tick()
    n = n + 1
    if n >= 200 then n = 0; spark_push(tonumber(ces.hyle.height()) or 0) end
  end)

  ces.log("hylenet: started '" .. ces.hyle.chain_id() .. "' with " .. #V .. " validators")
  return "started '" .. ces.hyle.chain_id() .. "'"
end

local autostarted = false

-- Idempotent: whichever of the config push or the deferred fallback arrives first boots
-- the chain, and the other becomes a no-op.
local function maybe_autostart()
  if autostarted then return end
  autostarted = true
  if has_binding() and num("autostart", 1) ~= 0 then
    ces.log("hylenet: " .. do_start())
  end
end

local function do_stop()
  if not running then return "not running" end
  running = false
  if heartbeat then ces.cancel(heartbeat); heartbeat = nil end
  ces.hyle.net.stop()
  height_spark = {}
  ces.log("hylenet: stopped")
  return "stopped"
end

-- ---------------------------------------------------------------------------
-- The line protocol
-- ---------------------------------------------------------------------------

local cmds = {}

function cmds.info()
  local i = ces.hyle.info()
  if not i then return "err no_chain" end
  return string.format(
    "ok chain=%s height=%d accounts=%d entries=%d txs=%d mempool=%d validators=%d quorum=%d " ..
    "sudo_pending=%d sudo_minted=%d balance=%d last_block=%d self=%s app_hash=%s",
    i.chain_id, i.height, i.accounts, i.entries, i.txs, i.mempool, i.validators, i.quorum,
    i.sudo_pending, i.sudo_minted, i.balance, i.last_block_time, hex(i.self), hex(i.app_hash))
end

function cmds.config()
  local c = ces.hyle.config()
  if not c then return "err no_chain" end
  return string.format(
    "ok fee_transfer=%d fee_entry=%d fee_sudo=%d rent_rate=%d rip_bounty=%d " ..
    "sudo_ttl_secs=%d member_cap=%d member_floor=%d max_value_bytes=%d",
    c.fee_transfer, c.fee_entry, c.fee_sudo, c.rent_rate, c.rip_bounty,
    c.sudo_ttl_secs, c.member_cap, c.member_floor, c.max_value_bytes)
end

cmds["self"] = function()
  return "ok " .. hex(ces.hyle.self())
end

function cmds.height()
  return "ok " .. string.format("%d", ces.hyle.height())
end

function cmds.account(conn, rest)
  local pk = unhex(rest:match("^(%S+)"))
  if not pk or #pk ~= 32 then return "err bad_pubkey" end
  local a = ces.hyle.account(pk)
  if not a then return "err no_chain" end
  return string.format("ok balance=%d sequence=%d exists=%d",
                       a.balance, a.sequence, a.exists and 1 or 0)
end

function cmds.entry(conn, rest)
  local name = rest:match("^(%S+)")
  if not name then return "err bad_name" end
  if name:sub(1, 4) == "hex:" then
    name = unhex(name:sub(5))
    if not name then return "err bad_hex_name" end
  end
  local e = ces.hyle.entry(name)
  if not e then return "err not_found" end
  return string.format("ok owner=%s balance=%d created=%d modified=%d rent=%d payload=%s",
                       hex(e.owner), e.balance, e.created, e.last_modified, e.last_rent,
                       hex(e.payload))
end

function cmds.txr(conn, rest)
  local id = unhex(rest:match("^(%S+)"))
  if not id or #id ~= 32 then return "err bad_txid" end
  local r = ces.hyle.tx_result(id)
  if not r then return "err not_found" end
  return string.format("ok height=%d applied=%d", r.height, r.applied and 1 or 0)
end

-- The carrier: opaque bytes in, tx ids out. We do not parse them and we could not have
-- signed them.
function cmds.submit(conn, rest)
  local raw = unhex(rest:match("^(%S+)"))
  if not raw then return "err bad_hex" end
  local ids, err = ces.hyle.submit(raw)
  if not ids then return "err " .. tostring(err) end
  local out = {}
  for _, id in ipairs(ids) do out[#out + 1] = hex(id) end
  return "ok " .. table.concat(out, " ")
end

-- Hand the node/validator private key to the owner, and only the owner. It is absolute chain
-- authority: whoever holds it is the validator and can mint or sudo. The owner then loads it
-- into cesh and acts as the node (`cesh hyle <pid> mint <to> <amount>`). Minting is a validator
-- op the chain gates; there is no path for a non-validator caller to create money.
function cmds.nodekey(conn)
  if not conn.pubkey or #conn.pubkey ~= 32 or hex(conn.pubkey) ~= hex(ces.owner_pubkey()) then
    return "err not_owner"
  end
  return "ok " .. hex(ces.hyle.self_secret())
end

-- Membership governance (owner only): this operator votes to add or remove a validator by its
-- 32-byte server pubkey. The change applies once a quorum of the current validators has voted.
local function gov_vote(conn, rest, fn)
  if not conn.pubkey or #conn.pubkey ~= 32 or hex(conn.pubkey) ~= hex(ces.owner_pubkey()) then
    return "err not_owner"
  end
  local pk = unhex((rest or ""):match("^(%x+)"))
  if not pk or #pk ~= 32 then return "err bad_pubkey" end
  return fn(pk) and "ok voted" or "err vote_failed"
end
function cmds.vote_add(conn, rest)    return gov_vote(conn, rest, ces.hyle.vote_add) end
function cmds.vote_remove(conn, rest) return gov_vote(conn, rest, ces.hyle.vote_remove) end

local function dispatch(conn, line)
  local cmd, rest = line:match("^(%S+)%s*(.*)$")
  if not cmd then return nil end
  local h = cmds[cmd:lower()]
  if not h then return "err unknown_command" end
  if not has_binding() then return "err no_binding (build the node with --hyle)" end
  if not running and cmd:lower() ~= "self" then
    -- Carry the reason: a genesis the chain refused is the usual one, and a bare
    -- "no_chain" sends the caller looking in the wrong place.
    return "err no_chain" .. (last_err and (" " .. last_err) or "")
  end
  local ok, res = pcall(h, conn, rest or "")
  if not ok then return "err " .. tostring(res) end
  return res
end

local function serve()
  ces.conn.set_listener{
    on_open = function(conn)
      bufs[conn.id] = ""
    end,
    on_data = function(conn, data)
      local buf = (bufs[conn.id] or "") .. data
      while true do
        local i = buf:find("\n", 1, true)
        if not i then break end
        local line = (buf:sub(1, i - 1):gsub("\r$", ""))
        buf = buf:sub(i + 1)
        if #line > 0 then
          local reply = dispatch(conn, line)
          if reply then conn:write(reply .. "\n") end
        end
      end
      bufs[conn.id] = buf
    end,
    on_close = function(conn)
      bufs[conn.id] = nil
    end,
  }
end

-- ---------------------------------------------------------------------------
-- Admin panel
-- ---------------------------------------------------------------------------

local function build_panel()
  return mene.app{
    model = { last_msg = "" },
    view = function(m)
      local binding = has_binding()
      local state = not binding and "no binding" or (running and "running" or "stopped")
      local tone = running and "ok" or (binding and "warn" or "err")
      local body = {}

      if running then
        local i = ces.hyle.info()
        body[#body + 1] = mene.grid({ cols = 4, gap = 12 },
          mene.metric({ label = "height", value = string.format("%d", i.height),
                        spark = height_spark, tone = "info" }),
          mene.stat({ label = "entries", value = string.format("%d", i.entries) }),
          mene.stat({ label = "accounts", value = string.format("%d", i.accounts) }),
          mene.stat({ label = "ops in blocks", value = string.format("%d", i.txs) }))
        body[#body + 1] = mene.kv({ rows = {
          { "chain", i.chain_id },
          { "validators", string.format("%d (quorum %d)", i.validators, i.quorum) },
          { "sudo pending", string.format("%d", i.sudo_pending) },
          { "minted by sudo", string.format("%d", i.sudo_minted) },
          { "validator balance", string.format("%d", i.balance) },
          { "mempool", string.format("%d", i.mempool) },
          { "last block", string.format("%d", i.last_block_time) },
          { "app hash", hex(i.app_hash) },
        } })
      elseif not binding then
        body[#body + 1] = mene.alert({ tone = "err", title = "ces.hyle absent" },
          "build the node with --hyle to host a chain")
      else
        body[#body + 1] = mene.text({ tone = "muted" },
          "configured chain: " .. (cfg.chain_id or "hylenet") ..
          " -- edit Config below, then Start.")
      end

      if last_err then
        body[#body + 1] = mene.alert({ tone = "err", title = "start failed" }, last_err)
      end

      body[#body + 1] = mene.stack({ gap = 4 },
        mene.text({ tone = "muted" }, "validator pubkey (this program; also its CES account)"),
        mene.text({ copy = true, tone = "code" },
          ces.program_pubkey and hex(ces.program_pubkey()) or "?"))

      body[#body + 1] = mene.row({ gap = 8 },
        mene.button({ on = "start", kind = "primary",
                      disabled = running or not binding }, "Start chain"),
        mene.button({ on = "stop", kind = "danger", disabled = not running,
                      confirm = "Stop the chain? Its state is in RAM and will be lost." },
                    "Stop chain"))

      body[#body + 1] = mene.section({ title = "genesis / economy (persists; applied on Start)" },
        mene.form({ on = "cfg" },
          mene.grid({ cols = 4, gap = 10 },
            mene.field({ name = "chain_id", label = "chain id",
                         value = cfg.chain_id or "hylenet" }),
            mene.field({ name = "block_pace_ms", kind = "number",
                         label = "block pace ms", value = num("block_pace_ms", 1000) }),
            mene.field({ name = "consensus_timeout_ms", kind = "number",
                         label = "consensus timeout ms (no-activity round timeout)",
                         value = num("consensus_timeout_ms", 1000) }),
            mene.field({ name = "validators",
                         label = "validators (space-separated 64-hex server keys)",
                         value = cfg.validators or "" }),
            mene.field({ name = "credit_autofill_ceiling", kind = "number",
                         label = "autofill ceiling (0=off)", value = num("credit_autofill_ceiling", 0) }),
            mene.field({ name = "refill_rate", kind = "number",
                         label = "autofill refill per block", value = num("refill_rate", 0) }),
            mene.field({ name = "fee_transfer", kind = "number",
                         label = "fee transfer", value = num("fee_transfer", 10) }),
            mene.field({ name = "fee_entry", kind = "number",
                         label = "fee entry", value = num("fee_entry", 10) }),
            mene.field({ name = "fee_sudo", kind = "number",
                         label = "fee sudo", value = num("fee_sudo", 1) }),
            mene.field({ name = "rent_rate", kind = "number",
                         label = "rent per byte-second", value = num("rent_rate", 1) }),
            mene.field({ name = "rip_bounty", kind = "number",
                         label = "rip bounty", value = num("rip_bounty", 10) }),
            mene.field({ name = "sudo_ttl_secs", kind = "number",
                         label = "sudo timeout secs (0=never)", value = num("sudo_ttl_secs", 0) }),
            mene.field({ name = "snapshot_interval", kind = "number",
                         label = "snapshot every N blocks (0=off)", value = num("snapshot_interval", 0) }),
            mene.field({ name = "block_retention", kind = "number",
                         label = "blocks kept in RAM", value = num("block_retention", 1024) }),
            mene.field({ name = "autostart", kind = "number",
                         label = "autostart (0/1)", value = num("autostart", 1) })),
          mene.submit({ kind = "primary" }, "Apply + save")))

      if m.last_msg ~= "" then
        body[#body + 1] = mene.text({ tone = "muted" }, m.last_msg)
      end

      return mene.card({ title = "HyleNet",
                         subtitle = "multi-node hyle chain over the CES server peer mesh" },
        mene.row({ gap = 8 }, mene.badge({ tone = tone }, state)),
        unpack(body))
    end,
    update = function(ev, m)
      if ev.on == "start" then
        m.last_msg = do_start()
      elseif ev.on == "stop" then
        m.last_msg = do_stop()
      elseif ev.on == "cfg" and type(ev.value) == "table" then
        local keys = { "chain_id", "validators", "block_pace_ms", "consensus_timeout_ms",
                       "fee_transfer", "fee_entry", "fee_sudo", "rent_rate", "rip_bounty",
                       "member_cap", "member_floor", "max_state_bytes", "credit_autofill_ceiling",
                       "refill_rate", "sudo_ttl_secs", "snapshot_interval", "block_retention",
                       "autostart" }
        local c, lines = {}, {}
        for _, k in ipairs(keys) do
          c[k] = tostring(ev.value[k] or "")
          lines[#lines + 1] = k .. " = " .. c[k]
        end
        cfg = c
        if ces.extension_admin.save_config then
          ces.extension_admin.save_config(table.concat(lines, "\n") .. "\n")
          m.last_msg = "config saved; applied on the next Start"
        else
          m.last_msg = "config stored for this run (host cannot persist)"
        end
      end
      return m
    end,
  }
end

-- ---------------------------------------------------------------------------

local spec = {
  status = function()
    if not running then
      return {
        state            = has_binding() and "stopped" or "no ces.hyle (needs --hyle node)",
        configured_chain = cfg.chain_id or "hylenet",
        last_error       = last_err or "",
      }
    end
    local i = ces.hyle.info()
    return {
      state       = "running",
      chain       = i.chain_id,
      height      = string.format("%d", i.height),
      accounts    = string.format("%d", i.accounts),
      entries     = string.format("%d", i.entries),
      txs         = string.format("%d", i.txs),
      mempool     = string.format("%d", i.mempool),
      validators  = string.format("%d", i.validators),
      quorum      = string.format("%d", i.quorum),
      sudo_pending = string.format("%d", i.sudo_pending),
      sudo_minted = string.format("%d", i.sudo_minted),
      balance     = string.format("%d", i.balance),
      last_block  = string.format("%d", i.last_block_time),
      app_hash    = hex(i.app_hash),
      self        = hex(i.self),
    }
  end,

  commands = {
    { id = "start", label = "Start chain" },
    { id = "stop",  label = "Stop chain"  },
  },
  on_command = function(id)
    if id == "start" then return do_start()
    elseif id == "stop" then return do_stop() end
    return "unknown command: " .. tostring(id)
  end,

  -- Autostart cannot happen at load time: the host queues the /s/hylenet.conf push at
  -- REGISTER and the child only dispatches it once the run loop is pumping, so starting
  -- before then boots the chain on defaults and quietly ignores the operator's genesis.
  -- Start when the config lands instead. If there is no conf file the host pushes nothing
  -- and this never fires, so a short deferred fallback below covers that case; whichever
  -- gets there first is the only one that runs.
  config_defaults = table.concat({
    "# HyleNet: a multi-node hyle chain. The validator identity is this CES SERVER's key, and",
    "# consensus rides the CES server peer mesh, so this node must be a mutual CES peer of the",
    "# other validators. Ship the SAME config (chain_id, validators, economy) to every node.",
    "chain_id = hylenet",
    "# the validator set: space-separated 64-hex CES server pubkeys, INCLUDING this node's own.",
    "validators =",
    "block_pace_ms = 1000",
    "# a consensus round with NO message activity for this long delivers a timeout and moves on.",
    "# WAN-safe default; must exceed a few inter-validator round-trips or rounds change prematurely.",
    "consensus_timeout_ms = 1000",
    "# 1 = boot the chain when the extension loads (needs validators set + the peers linked)",
    "autostart = 1",
    "# funding is per-block validator autofill (through consensus). ceiling 0 = off.",
    "credit_autofill_ceiling = 0",
    "refill_rate = 0",
    "# economy. With rent on, the chain rejects a genesis where rip_bounty > min(fee_transfer,",
    "# fee_entry): a bounty worth more than the fee to create a rippable entry mints money out",
    "# of the cull.",
    "fee_transfer = 10",
    "fee_entry = 10",
    "# per-op fee for a sudo propose/approve",
    "fee_sudo = 1",
    "rent_rate = 1",
    "rip_bounty = 10",
    "# validator-set bounds -- consensus rules, all nodes must agree.",
    "member_cap = 21",
    "member_floor = 1",
    "# hard ceiling on total state RAM in bytes; 0 = unbounded. A full chain refuses new",
    "# entries and new accounts (existing entries still update; rip frees space).",
    "max_state_bytes = 0",
    "# a pending sudo proposal past this age cannot execute and is cleared. 0 = never.",
    "sudo_ttl_secs = 0",
    "snapshot_interval = 0",
    "block_retention = 1024",
    "",
  }, "\n"),
  on_config = function(c)
    cfg = c
    maybe_autostart()
  end,
}

if mene then spec.panel = build_panel() end
ces.extension_admin(spec)

ces.spawn(function()
  ces.sleep(250)
  maybe_autostart()
end)

-- Paid purchase over the compute CALL verb: sell the caller `value` hyle from the
-- validator balance with a max transfer (never fails on a shortfall), 1:1. The
-- payer key is its hyle account (one key, two ledgers). Reply: the caller's hyle
-- balance after settlement.
function on_l2call(memo, ctx)
  if not (has_binding() and running) then return "err no_chain" end
  if not ctx.payer or #ctx.payer ~= 32 then return "err bad_payer" end
  -- Submit the sale into the mempool and return the tx id. We do not wait on consensus:
  -- the buyer polls `account <yourkey>` (or `txr <id>`) to see when the credit lands.
  local ids, err = ces.hyle.submit(ces.hyle.op.transfer{ to = ctx.payer, amount = ctx.value, max = true })
  if not ids then return "err " .. tostring(err) end
  return "ok " .. hex(ids[1])
end

serve()
ces.run()

end

CES_MANIFEST = { name = "HyleNet", version = "0.1", description = "A multi-node hyle-services blockchain hosted inside cesluajitd over the ces.hyle binding. The validator identity is the CES SERVER key (one key, two ledgers) and consensus rides the CES server peer mesh, so the validator set is the CES servers that are mutual peers and carry the same genesis (chain_id, validators, economy). No transport of its own. Funding is per-block validator autofill. Serves the same ces.conn line protocol as HyleSolo: clients sign their own ops and submit them as opaque bytes. Requires a cesluajitd built with --hyle on an ed25519 server key." }
return require("main")
