-- generated by cesdk 0.1.0, do not edit
-- project: hylesolo 0.1

local __mods, __cache = {}, {}
local function require(name)
  local c = __cache[name]
  if c ~= nil then return c end
  local f = __mods[name]
  if not f then error("cesdk bundle: module '" .. name .. "' not found", 2) end
  local r = f()
  if r == nil then r = true end
  __cache[name] = r
  return r
end

__mods["cesdk.manifest"] = function() return { name = "hylesolo", version = "0.1", protocols = {  } } end

__mods["main"] = function()
-- HyleSolo - a CES extension that hosts a SINGLE-NODE (transportless) hyle-services
-- blockchain inside cesluajitd. Enabling the extension does NOT run a chain; it just
-- loads and lets you set the config. Two admin buttons drive it:
--   Start  - boot a node from the current config and heartbeat blocks.
--   Stop   - tear the node down.
-- Disabling / uninstalling the extension kills this cesluajitd process, which
-- destroys the in-process node too, so that also stops the chain.
--
-- Default config is a 1-node chain: this program's own key is the sole validator
-- and proposer (its own 1-of-1 quorum), so it commits a block every block_pace_ms
-- with no peers. The extension config IS the hyle genesis/economy config.
--
-- Runs over the ces.hyle.solo binding (extension-only / privileged /s/), which needs
-- a cesluajitd built with --hyle. The `hyle` name/namespace is reserved for the future
-- transport-enabled multi-node chain; HyleSolo runs side-by-side with it.

local cfg = {}
local running = false
local heartbeat_armed = false

-- Pubkeys arrive as raw 32-byte strings; hex them for display.
local function hex(s)
  return (s:gsub(".", function(c) return string.format("%02x", c:byte()) end))
end

-- Read a scalar meter binding, tolerating an older node that lacks it (-> "?").
local function meter(fn)
  return fn and tostring(fn()) or "?"
end

local function has_binding()
  return ces.hyle ~= nil and ces.hyle.solo ~= nil and ces.hyle.solo.start ~= nil
end

local function do_start()
  if running then return "already running (height " .. tostring(ces.hyle.solo.height()) .. ")" end
  if not has_binding() then return "ces.hyle.solo absent -- build the node with --hyle" end
  local pace = tonumber(cfg.block_pace_ms) or 1000
  ces.hyle.solo.start{
    chain_id     = cfg.chain_id or "hylesolo",
    alloc        = tonumber(cfg.alloc) or 1000000000,   -- genesis funds the program's own account
    fee_transfer = tonumber(cfg.fee_transfer) or 1,
    fee_entry    = tonumber(cfg.fee_entry) or 1,
    fee_mint     = tonumber(cfg.fee_mint) or 1,
    reward_base  = tonumber(cfg.reward_base) or 2,
  }
  running = true
  -- Arm the heartbeat exactly once; the tick is a no-op while stopped. Solo is its
  -- own quorum, so a tick proposes+precommits+commits synchronously and returns --
  -- it never blocks the cooperative VM.
  if not heartbeat_armed then
    ces.every(pace, function() if running then ces.hyle.solo.tick() end end)
    heartbeat_armed = true
  end
  ces.log("hylesolo: started chain '" .. (cfg.chain_id or "hylesolo") .. "', one block every " .. pace .. "ms")
  return "started chain '" .. (cfg.chain_id or "hylesolo") .. "'"
end

local function do_stop()
  if not running then return "not running" end
  running = false
  if ces.hyle and ces.hyle.solo and ces.hyle.solo.stop then ces.hyle.solo.stop() end
  ces.log("hylesolo: stopped")
  return "stopped"
end

ces.extension_admin{
  status = function()
    if not running then
      return {
        state            = has_binding() and "stopped" or "no ces.hyle.solo (needs --hyle node)",
        configured_chain = cfg.chain_id or "hylesolo",
      }
    end
    return {
      state      = "running",
      chain      = ces.hyle.solo.chain_id(),
      height     = tostring(ces.hyle.solo.height()),
      balance    = meter(ces.hyle.solo.balance),   -- the validator's own minted balance
      accounts   = meter(ces.hyle.solo.accounts),  -- RAM-state cell counts (a / e)
      entries    = meter(ces.hyle.solo.entries),
      txs        = meter(ces.hyle.solo.txs),        -- lifetime meters, reset on Start
      queries    = meter(ces.hyle.solo.queries),
      last_block = meter(ces.hyle.solo.last_block_time),
      validators = "1 (self)",
      self       = ces.program_pubkey and hex(ces.program_pubkey()) or "?",
    }
  end,

  commands = {
    { id = "start", label = "Start chain" },
    { id = "stop",  label = "Stop chain"  },
  },
  on_command = function(id)
    if id == "start" then return do_start()
    elseif id == "stop" then return do_stop() end
    return "unknown command: " .. tostring(id)
  end,

  config_defaults = table.concat({
    "# HyleSolo single-node blockchain -- this program's own key is the sole validator.",
    "chain_id = hylesolo",
    "block_pace_ms = 1000",
    "# genesis allocation to the program's own account (whole credits)",
    "alloc = 1000000000",
    "# economy fees + floor-difficulty mint reward (whole credits)",
    "fee_transfer = 1",
    "fee_entry = 1",
    "fee_mint = 1",
    "reward_base = 2",
    "",
  }, "\n"),
  on_config = function(c) cfg = c end,   -- store only; the chain runs on Start, not on enable
}

ces.run()

end

CES_MANIFEST = { name = "HyleSolo", version = "0.1", description = "Boots a SINGLE-NODE (transportless) hyle-services blockchain inside cesluajitd, over the ces.hyle.solo binding. The extension's own program key is the sole validator, producing one block every block_pace_ms. The extension config IS the hyle genesis/economy config. Requires a cesluajitd built with --hyle. Reserves the `hyle` name for the future multi-node chain; runs side-by-side with it." }
return require("main")
