-- generated by cesdk 0.1.0, do not edit
-- project: monitor 0.1.0

local __mods, __cache = {}, {}
local function require(name)
  local c = __cache[name]
  if c ~= nil then return c end
  local f = __mods[name]
  if not f then error("cesdk bundle: module '" .. name .. "' not found", 2) end
  local r = f()
  if r == nil then r = true end
  __cache[name] = r
  return r
end

__mods["cesdk.manifest"] = function() return { name = "monitor", version = "0.1.0", protocols = {  } } end

__mods["main"] = function()
-- monitor - a public, read-only web dashboard for this CES server, served
-- through cesweb (the /i/ scope). Each HTTP GET renders a fresh snapshot: server
-- stats (when ces.server_info is available) plus the peer table. No WebSocket
-- and no polling; the browser refreshes to re-query. All data is public.

local web = require("web")
local json = require("json")
local snapshot = require("snapshot")
local dash = require("dash")

web.serve{
  on_request = function(_req)
    return web.html(dash.page(json.encode(snapshot.gather())))
  end,
}

if ces.manifest then
  pcall(ces.manifest, { name = "monitor", version = "0.1.0",
                        description = "public read-only server and peering monitor" })
end

web.run()

end

__mods["web"] = function()
-- web.lua - HTTP/1.1 + WebSocket server machinery over ces.conn.
--
-- Rides the cesweb /i/ proxy. cesweb is the browser's TLS peer, so it terminates
-- the wire protocol and hands a compute program one of two shapes on a ces.conn:
--
--   HTTP  : raw request bytes ("GET / HTTP/1.1\r\n...\r\n\r\n"); answer once with
--           an HTTP response, then close (Connection: close).
--   WebSocket : length-framed messages, [u32 BE len][payload]. Frame 0 is the
--           handshake request (so the program can route by path / read cookies);
--           frames 1..N are message payloads. A payload sent back is delivered to
--           the browser as one text WebSocket message.
--
-- The two are told apart by the first byte of the first chunk: an HTTP method is
-- an uppercase ASCII letter (>= 0x41); a frame length's high byte is 0x00
-- (messages are far under 16 MiB). So byte0 == 0 => WebSocket, else => HTTP.
--
-- Usage:
--   local web = require("web")
--   web.serve{
--     on_request   = function(req) return web.html("<h1>hi</h1>") end,
--     on_websocket = function(ws)
--       ws.on_message = function(msg) ws.send("you said: "..msg) end
--     end,
--   }
--   web.run()   -- = ces.run()
--
--   req = { method, target, path, query, headers = {lowercased->value}, body }
--   ws  = { id, path, query, headers, send(msg), close(), on_message, on_close }

local M = {}

-- u32 big-endian pack/unpack via arithmetic (doubles are exact to 2^53).
local function u32be(n)
  return string.char(math.floor(n / 16777216) % 256,
                     math.floor(n / 65536) % 256,
                     math.floor(n / 256) % 256,
                     n % 256)
end
local function rd_u32be(s, i)          -- i = 1-based index of the length's first byte
  local a, b, c, d = s:byte(i, i + 3)
  return ((a * 256 + b) * 256 + c) * 256 + d
end

-- Parse an HTTP request (or the WebSocket handshake request in frame 0).
local function parse_request(raw)
  local head = raw:match("^(.-)\r\n\r\n")
  if not head then return nil end
  local body = raw:sub(#head + 5)
  local first = head:match("^(.-)\r\n") or head
  local method, target = first:match("^(%S+)%s+(%S+)")
  if not method then return nil end
  local path, query = target:match("^([^?]*)%??(.*)$")
  local headers = {}
  for line in head:gmatch("\r\n([^\r\n]+)") do
    local k, v = line:match("^([^:]+):%s*(.*)$")
    if k then headers[k:lower()] = v end
  end
  return { method = method, target = target, path = path, query = query,
           headers = headers, body = body }
end

local REASON = { [200] = "OK", [400] = "Bad Request", [404] = "Not Found",
                 [500] = "Internal Server Error" }

-- Build an HTTP/1.1 response from a string or a { status, headers, body } table.
local function build_response(resp)
  if type(resp) == "string" then resp = { body = resp } end
  resp = resp or { status = 404 }
  local status = resp.status or 200
  local reason = resp.reason or REASON[status] or ""
  local body = resp.body or ""
  local out = { ("HTTP/1.1 %d %s\r\n"):format(status, reason) }
  local have_ct = false
  if resp.headers then
    for k, v in pairs(resp.headers) do
      if k:lower() == "content-type" then have_ct = true end
      out[#out + 1] = k .. ": " .. tostring(v) .. "\r\n"
    end
  end
  if not have_ct then out[#out + 1] = "Content-Type: text/html; charset=utf-8\r\n" end
  out[#out + 1] = "Content-Length: " .. #body .. "\r\n"
  out[#out + 1] = "Connection: close\r\n\r\n"
  out[#out + 1] = body
  return table.concat(out)
end

-- Response helpers.
function M.html(body, status)
  return { status = status or 200, body = body or "",
           headers = { ["Content-Type"] = "text/html; charset=utf-8" } }
end
function M.text(body, status)
  return { status = status or 200, body = body or "",
           headers = { ["Content-Type"] = "text/plain; charset=utf-8" } }
end
function M.response(status, body, headers)
  return { status = status, body = body, headers = headers }
end

local function make_ws(conn, hs)
  local ws = {
    id = conn.id,
    path = hs and hs.path or "/",
    query = hs and hs.query or "",
    headers = hs and hs.headers or {},
    on_message = nil,
    on_close = nil,
  }
  function ws.send(msg)
    msg = tostring(msg)
    return conn:write(u32be(#msg) .. msg)
  end
  function ws.close() conn:close() end
  return ws
end

-- serve{ on_request, on_websocket }: arm the ces.conn listener and dispatch.
function M.serve(opts)
  opts = opts or {}
  local on_request = opts.on_request
  local on_websocket = opts.on_websocket
  local conns = {}                        -- conn.id -> per-connection state

  local function handle_http(st, conn)
    if not st.buf:find("\r\n\r\n", 1, true) then return end   -- headers incomplete
    local req = parse_request(st.buf)
    if not req then
      st.done = true
      conn:write(build_response(M.response(400, "bad request")))
      conn:close()
      return
    end
    -- Wait for the full request body (POST/PUT/...) before dispatching.
    local clen = tonumber(req.headers["content-length"]) or 0
    if #req.body < clen then return end
    st.done = true
    local resp
    if on_request then
      local ok, r = pcall(on_request, req)
      resp = ok and r or M.response(500, "internal error")
    end
    conn:write(build_response(resp))
    conn:close()
  end

  local function handle_ws(st, conn)
    while true do
      if #st.buf < 4 then return end
      local len = rd_u32be(st.buf, 1)
      if #st.buf < 4 + len then return end
      local payload = st.buf:sub(5, 4 + len)
      st.buf = st.buf:sub(5 + len)
      if not st.ws then
        local ws = make_ws(conn, parse_request(payload))   -- frame 0 = handshake
        st.ws = ws
        if on_websocket then pcall(on_websocket, ws) end
      elseif st.ws.on_message then
        pcall(st.ws.on_message, payload)
      end
    end
  end

  ces.conn.set_listener{
    on_open = function(conn) conns[conn.id] = { buf = "" } end,
    on_data = function(conn, data)
      local st = conns[conn.id]
      if not st then st = { buf = "" }; conns[conn.id] = st end
      if st.done then return end
      st.buf = st.buf .. data
      if not st.mode then
        local b0 = st.buf:byte(1)
        if b0 == nil then return end
        st.mode = (b0 == 0) and "ws" or "http"
      end
      if st.mode == "http" then handle_http(st, conn) else handle_ws(st, conn) end
    end,
    on_close = function(conn)
      local st = conns[conn.id]
      if st and st.ws and st.ws.on_close then pcall(st.ws.on_close) end
      conns[conn.id] = nil
    end,
  }
end

function M.run() return ces.run() end

return M

end

__mods["json"] = function()
-- json.lua - minimal JSON encoder. Encode only: a program builds tables and
-- ships them to a browser, which parses natively. No decoder (nothing on the
-- server needs to read JSON). Arrays are contiguous 1..n integer-keyed tables;
-- everything else is an object.

local M = {}

local ESC = { ['"'] = '\\"', ['\\'] = '\\\\', ['\n'] = '\\n', ['\r'] = '\\r',
              ['\t'] = '\\t', ['\b'] = '\\b', ['\f'] = '\\f' }
local function esc(s)
  return (s:gsub('[%z\1-\31\\"]', function(c)
    return ESC[c] or string.format('\\u%04x', c:byte())
  end))
end

local function is_array(t)
  local n = 0
  for k in pairs(t) do
    if type(k) ~= "number" then return false end
    n = n + 1
  end
  return n == #t
end

local function encode(v)
  local t = type(v)
  if t == "nil" then return "null"
  elseif t == "boolean" then return v and "true" or "false"
  elseif t == "number" then
    if v ~= v or v == math.huge or v == -math.huge then return "null" end
    return string.format("%.14g", v)
  elseif t == "string" then return '"' .. esc(v) .. '"'
  elseif t == "table" then
    local out = {}
    if is_array(v) then
      for i = 1, #v do out[i] = encode(v[i]) end
      return "[" .. table.concat(out, ",") .. "]"
    end
    for k, val in pairs(v) do
      out[#out + 1] = '"' .. esc(tostring(k)) .. '":' .. encode(val)
    end
    return "{" .. table.concat(out, ",") .. "}"
  end
  return "null"
end

M.encode = encode
return M

end

__mods["snapshot"] = function()
-- snapshot.lua - gather a public, read-only view of this CES server. Every field
-- is already publicly readable: the peer table is an unsigned public read, the
-- server pubkey is the public identity, and ces.server_info (when present) is the
-- host's own published stats. No balances, keys, or privileged peer-control.

local M = {}

local function hex(s)
  if not s or s == "" then return "" end
  return (s:gsub('.', function(c) return string.format('%02x', c:byte()) end))
end

-- First 8 bytes of a pubkey; the ledger keys accounts by the same prefix.
local function short(s) return hex(s):sub(1, 16) end

function M.gather()
  local peers, rows = ces.peers() or {}, {}
  local pow_in, pow_out, reachable, outbound, inbound = 0, 0, 0, 0, 0
  for _, p in ipairs(peers) do
    pow_in = pow_in + (p.inbound_pow or 0)
    pow_out = pow_out + (p.outbound_pow or 0)
    if p.reachable then reachable = reachable + 1 end
    if p.outbound then outbound = outbound + 1 end
    if p.inbound then inbound = inbound + 1 end
    rows[#rows + 1] = {
      pubkey = hex(p.pubkey), addr = p.address or "",
      outbound = p.outbound or false, inbound = p.inbound or false,
      reachable = p.reachable or false, verified = p.verified or false,
      rpc_port = p.rpc_port or 0, pow_in = p.inbound_pow or 0, pow_out = p.outbound_pow or 0,
    }
  end

  local me = ces.owner_pubkey and ces.owner_pubkey() or nil
  return {
    self = hex(me), self_id = short(me),
    server = ces.server_info and ces.server_info() or nil,   -- host stats when the intrinsic exists
    peers = rows,
    metrics = { peers = #peers, outbound = outbound, inbound = inbound,
                reachable = reachable, pow_in = pow_in, pow_out = pow_out },
  }
end

return M

end

__mods["dash"] = function()
-- dash.lua - the snapshot dashboard page. The server embeds the current state as
-- a JS object and the script renders it once, on load: stat cards and a peer
-- table. No canvas, no WebSocket, no polling; the refresh button re-queries.
-- Wide/ultrawide cards give large counts room (like the web admin overview).

local M = {}

function M.page(data_json)
  data_json = (data_json or "{}"):gsub("</", "<\\/")   -- keep embedded data from closing the script
  local out = ([==[<!doctype html>
<html lang=en><meta charset=utf-8>
<meta name=viewport content="width=device-width,initial-scale=1">
<title>CES server monitor</title>
<style>
  :root{color-scheme:dark}
  html,body{margin:0;background:#0d0f14;color:#e6e9ef;font:14px/1.5 system-ui,sans-serif}
  #wrap{max-width:900px;margin:0 auto;padding:1.2rem 1rem 3rem}
  .bar{display:flex;align-items:center;justify-content:space-between}
  h1{font-size:1.15rem;font-weight:650;margin:.2rem 0}
  button{background:#1f6feb;color:#fff;border:0;border-radius:8px;padding:.45rem .9rem;font:inherit;cursor:pointer}
  .sub{color:#8b93a3;font-size:.85rem;margin:.3rem 0;word-break:break-all}
  .hello{color:#c9cedb;margin:.2rem 0 1rem}
  .cards{display:grid;grid-template-columns:repeat(auto-fill,minmax(110px,1fr));grid-auto-flow:dense;gap:.6rem;margin:1rem 0}
  .card{background:#161a22;border:1px solid #232833;border-radius:10px;padding:.7rem .8rem;min-width:0}
  .card.wide{grid-column:span 2}
  .card.ultrawide{grid-column:span 4}
  .card .v{font-size:1.4rem;font-weight:650;font-variant-numeric:tabular-nums;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
  .card .l{color:#8b93a3;font-size:.74rem;text-transform:uppercase;letter-spacing:.04em}
  table.peers{width:100%;border-collapse:collapse;font-size:.82rem;margin-top:1rem}
  table.peers th{text-align:left;color:#8b93a3;font-weight:600;padding:.3rem .5rem;border-bottom:1px solid #232833}
  table.peers td{padding:.25rem .5rem;font-variant-numeric:tabular-nums}
  table.peers .keyrow td{padding-top:.55rem;word-break:break-all}
  table.peers .datarow td{color:#8b93a3;border-bottom:1px solid #1c2029;padding-bottom:.55rem}
  .dot{display:inline-block;width:.6em;height:.6em;border-radius:50%;margin-right:.35em;vertical-align:middle}
  code{background:#ffffff10;padding:.05em .3em;border-radius:4px}
</style>
<div id=wrap>
  <div class=bar><h1>CES server monitor</h1><button onclick="location.reload()">refresh</button></div>
  <div class=sub>server <code id=self></code></div>
  <div class=sub id=ver></div>
  <div class=hello id=hello></div>
  <div class=cards id=cards></div>
  <table class=peers id=peers></table>
</div>
<script>
const D = __DATA__;
const S = D.server || {}, MET = D.metrics || {};
const $ = id => document.getElementById(id);
const esc = s => String(s).replace(/[&<>]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const fmtNum = n => Number(n).toLocaleString('en-US');
function card(l, v, cls){ return '<div class="card'+(cls?' '+cls:'')+'"><div class=v>'+esc(v)+'</div><div class=l>'+esc(l)+'</div></div>'; }

$('self').textContent = D.self || '?';
if (S.version) $('ver').textContent = 'version ' + S.version;
if (S.hello) $('hello').textContent = S.hello;

let c = '';
if (S.circulating != null)    c += card('circulating (cr)', fmtNum(Math.floor(S.circulating/1e8)), 'ultrawide');
if (S.accounts != null)       c += card('accounts', fmtNum(S.accounts), 'wide');
if (S.assets != null)         c += card('assets', fmtNum(S.assets), 'wide');
if (S.aliases != null)        c += card('aliases', fmtNum(S.aliases), 'wide');
if (S.tx_count != null)       c += card('transactions', fmtNum(S.tx_count), 'wide');
if (S.tps != null)            c += card('tps', fmtNum(S.tps));
if (S.min_difficulty != null) c += card('min diff', S.min_difficulty);
if (S.fee_tx != null)         c += card('fee tx', fmtNum(S.fee_tx), 'wide');
if (S.fee_query != null)      c += card('fee query', fmtNum(S.fee_query), 'wide');
c += card('peers', MET.peers||0) + card('reachable', MET.reachable||0) +
     card('outbound', MET.outbound||0) + card('inbound', MET.inbound||0);
$('cards').innerHTML = c;

const rows = (D.peers||[]).map(function(p){
  const dir = (p.outbound&&p.inbound)?'both':p.outbound?'out':p.inbound?'in':'-';
  return '<tr class=keyrow><td colspan=5><span class=dot style="background:'+
    (p.reachable?'#39d98a':'#6b7280')+'"></span><code>'+esc(p.pubkey||'')+'</code></td></tr>'+
    '<tr class=datarow><td>'+esc(p.addr||'-')+'</td><td>'+dir+'</td><td>'+esc(p.rpc_port||'-')+
    '</td><td>'+fmtNum(p.pow_in||0)+'</td><td>'+fmtNum(p.pow_out||0)+'</td></tr>';
}).join('');
$('peers').innerHTML = rows
  ? '<tr><th>address</th><th>dir</th><th>rpc</th><th>reserve in</th><th>reserve out</th></tr>' + rows
  : '<tr><td class=datarow style="color:#6b7280">no peers</td></tr>';
</script>
]==]):gsub("__DATA__", function() return data_json end)
  return out   -- gsub returns (string, count); return only the string
end

return M

end

CES_MANIFEST = { name = "monitor", version = "0.1.0", description = "" }
return require("main")
