-- generated by cesdk 0.1.0, do not edit
-- project: peerclusterer 0.1

local __mods, __cache = {}, {}
local function require(name)
  local c = __cache[name]
  if c ~= nil then return c end
  local f = __mods[name]
  if not f then error("cesdk bundle: module '" .. name .. "' not found", 2) end
  local r = f()
  if r == nil then r = true end
  __cache[name] = r
  return r
end

__mods["cesdk.manifest"] = function() return { name = "peerclusterer", version = "0.1", protocols = { "/peerclusterer/1" } } end

__mods["main"] = function()
-- peerclusterer - a privileged /s/ extension that nudges the host's peer table
-- into closed cliques (clusters) of a target size. Stigmergic and add-only: each
-- slow tick it (1) gossips its own peer list to its peers over the /ces/peer/1
-- mesh (the pheromone), (2) folds peers' gossiped lists into a 2-hop view, and
-- (3) makes ONE triadic-closure add toward closing a clique around itself. It
-- never removes a peer (committed reserves stay) and never exceeds the table
-- headroom. The decision rule is the pure clusterer.decide; this file is the
-- live wiring (mesh I/O, the tick, the operator contract).
--
-- Identity (CES_MANIFEST) is injected by the cesdk bundler from project.lua.

local clusterer = require("clusterer")
local admin     = require("admin")
local conf      = require("conf")

local SERVICE = "peerclusterer"   -- mesh service tag; same name on every node

-- ---------------------------------------------------------------------------
-- Pheromone wire format: [u16 count] then per peer [32 pubkey][u16 alen][addr].
-- Lua-to-Lua over the mesh (the host relays opaque bytes), so a plain
-- big-endian framing both ends share is all that is needed.
-- ---------------------------------------------------------------------------
local function put_u16(t, n)
  t[#t + 1] = string.char(math.floor(n / 256) % 256, n % 256)
end

-- Each peer entry: [32 pubkey][u8 flags][u16 alen][addr]. flags bit0 = "this
-- peer is a confirmed peerclusterer speaker" (I have heard its pheromone), so a
-- receiver learns a candidate's speaker status one hop before recruiting it.
local function encode_peers(peers, cap, heard)
  local out, n = {}, 0
  local body = {}
  for _, p in ipairs(peers) do
    if n >= cap then break end
    if p.pubkey and #p.pubkey == 32 and p.address and #p.address <= 65535 then
      body[#body + 1] = p.pubkey
      body[#body + 1] = string.char(heard[p.pubkey] and 1 or 0)
      put_u16(body, #p.address)
      body[#body + 1] = p.address
      n = n + 1
    end
  end
  put_u16(out, n)
  out[#out + 1] = table.concat(body)
  return table.concat(out)
end

local function decode_peers(b)
  local list = {}
  if not b or #b < 2 then return list end
  local count = b:byte(1) * 256 + b:byte(2)
  local off = 3
  for _ = 1, count do
    if off + 32 + 1 + 2 > #b + 1 then break end
    local pk = b:sub(off, off + 31); off = off + 32
    local flags = b:byte(off); off = off + 1
    local alen = b:byte(off) * 256 + b:byte(off + 1); off = off + 2
    if off + alen > #b + 1 then break end
    local addr = b:sub(off, off + alen - 1); off = off + alen
    list[#list + 1] = { pubkey = pk, address = addr,
                        speaker = (flags % 2) == 1 }
  end
  return list
end

-- ---------------------------------------------------------------------------
-- State: the observed environment, not authoritative cluster membership.
--   view    : pubkey -> array of that node's peer pubkeys (2-hop graph)
--   addr    : pubkey -> address (so a chosen candidate can be dialed/added)
--   heard   : pubkey -> true for peers whose pheromone I have received (a
--             confirmed speaker; only these count toward closing a cluster)
--   vouched : pubkey -> true for non-peer nodes a heard speaker flagged as
--             speakers (candidate eligibility; never recruit a non-speaker)
--   added_at: pubkey -> ms timestamp for peers the clusterer ITSELF added (so it
--             knows which peers it may reclaim, and when the settle window ends)
--   culled  : pubkey -> true for own adds reclaimed as duds (never re-recruit)
-- In-memory only (the clusterer does not persist; that is the grouper's job): on
-- restart it forgets its adds and re-converges from gossip, never culling a peer
-- it did not add this run.
-- ---------------------------------------------------------------------------
local view, addr, heard, vouched, added_at, culled = {}, {}, {}, {}, {}, {}

-- Config / defaults.
local cfg = conf.load("/s/peerclusterer.conf")
local function build_opts(c)
  return {
    group_size = conf.num(c, "group_size", 20),   -- clique size to close
    -- The server peer table is a fixed 100-persisted / 200-in-mem (server.h
    -- constants; not configurable). Cap at 80 so the clusterer always leaves a
    -- 20-slot buffer under the persisted 100 for discovery's peers, manual
    -- peers, and inbound-PoW churn.
    max_peers  = conf.num(c, "max_peers", 80),
    tick_ms    = conf.num(c, "tick_ms", 5000),    -- gossip + one move per tick
    gossip_cap = conf.num(c, "gossip_cap", 64),   -- peers per gossip frame
    -- A peer the clusterer added is a real cluster member only once it has
    -- reciprocated `peer_credit_target` lifetime inbound PoW (raw units) -- the
    -- "this peer is committed to the peering" signal (lifetime PoW, not balance:
    -- balance drains via transfers/gossip). Default 5 full credits = the bare
    -- minimum for meaningful comms. 0 = link-liveness only (tests).
    peer_credit_target = conf.num(c, "peer_credit_target", 500000000),
    -- Settle window before the clusterer reclaims one of its OWN adds that never
    -- became a real member. Long on purpose so links + PoW have ample time to
    -- form; only a truly dead peering is culled. Default 24h.
    dud_timeout_ms = conf.num(c, "dud_timeout_ms", 86400000),
  }
end
local opts = build_opts(cfg)

local me = ces.owner_pubkey and ces.owner_pubkey() or nil

-- Stats for the dashboard / console (observability, not decision state).
local stat = { ticks = 0, adds = 0, culls = 0, last = "init", core = 0, peers = 0 }

local function now_ms() return math.floor(ces.now() / 1000) end

-- My current pheromone: my peer list, each entry flagged if I have heard it.
local function my_frame()
  return encode_peers(ces.peers() or {}, opts.gossip_cap, heard)
end

-- Inbound pheromone: a peer's gossiped peer list. Hearing it confirms `from` is
-- a speaker; fold its list into the 2-hop view, record addresses, and note which
-- of its peers it vouches as speakers. On FIRST contact reply immediately so
-- mutual speaker-detection does not wait a whole tick.
ces.peer.listen(SERVICE, function(from, payload)
  local first = not heard[from]
  heard[from] = now_ms()   -- last-heard time: lets dud detection spot a member
                           -- that went silent, not just one that never spoke
  local list = decode_peers(payload)
  local pubs = {}
  for _, e in ipairs(list) do
    pubs[#pubs + 1] = e.pubkey
    addr[e.pubkey] = e.address
    if e.speaker then vouched[e.pubkey] = true end
  end
  view[from] = pubs
  if first then ces.peer.send(from, SERVICE, my_frame()) end
end)

-- The tick: gossip my list, refresh my own view, make one move.
local function tick()
  stat.ticks = stat.ticks + 1
  local peers = ces.peers() or {}
  stat.peers = #peers

  -- Record my own neighborhood, every peer's address, and per-peer lifetime
  -- inbound PoW (the econ signal for dud detection), and broadcast my list.
  local mypubs, pow = {}, {}
  for _, p in ipairs(peers) do
    if p.pubkey then
      mypubs[#mypubs + 1] = p.pubkey
      if p.address then addr[p.pubkey] = p.address end
      pow[p.pubkey] = p.inbound_pow or 0
    end
  end
  if me then view[me] = mypubs end

  -- Bound state to the live 2-hop neighborhood: forget any node that is neither
  -- a current peer nor named in some peer's gossiped list. Keeps the caches from
  -- growing without limit as the network churns. (added_at/culled for current
  -- peers stay; a culled node that leaves the view is forgotten -- a natural
  -- cooldown that lets it be reconsidered if it ever returns.)
  if me then
    local live = { [me] = true }
    for _, k in ipairs(mypubs) do live[k] = true end
    for _, list in pairs(view) do
      for _, q in ipairs(list) do live[q] = true end
    end
    for k in pairs(view)     do if not live[k] then view[k]     = nil end end
    for k in pairs(heard)    do if not live[k] then heard[k]    = nil end end
    for k in pairs(vouched)  do if not live[k] then vouched[k]  = nil end end
    for k in pairs(addr)     do if not live[k] then addr[k]     = nil end end
    for k in pairs(added_at) do if not live[k] then added_at[k] = nil end end
    for k in pairs(culled)   do if not live[k] then culled[k]   = nil end end
  end

  -- Reclaim duds: peers I added that, after the settle window, never became real
  -- members (not reciprocating, or under the lifetime-PoW target). Removing a
  -- dead peering destroys no value and frees a slot for a fitter peer.
  local duds = clusterer.find_duds(mypubs, heard, pow, added_at,
                                   now_ms(), opts.dud_timeout_ms,
                                   opts.peer_credit_target)
  for _, d in ipairs(duds) do
    if ces.remove_peer(d) then
      added_at[d] = nil
      culled[d] = true
      stat.culls = stat.culls + 1
    end
  end

  local frame = encode_peers(peers, opts.gossip_cap, heard)
  for _, p in ipairs(peers) do
    if p.pubkey then ces.peer.send(p.pubkey, SERVICE, frame) end
  end

  -- One move toward closing my clique.
  if me then
    local move = clusterer.decide(me, mypubs, view, heard, vouched, culled, opts)
    stat.core = move.size or 0
    if move.action == "add" and move.target and addr[move.target] then
      local ok = ces.add_peer(move.target, addr[move.target])
      if ok then
        added_at[move.target] = now_ms()   -- remember it is MY add, and when
        stat.adds = stat.adds + 1
        stat.last = "add(score=" .. tostring(move.score) .. ")"
      else
        stat.last = "add-failed"
      end
    else
      stat.last = move.reason or "idle"
    end
  end
end

-- Re-armable timer so tick_ms can be retuned live; a fault never kills it.
local timer
local function arm()
  if timer then ces.cancel(timer) end
  timer = ces.every(opts.tick_ms, function()
    local ok, err = pcall(tick)
    if not ok then ces.log("error", "peerclusterer: tick error: " .. tostring(err)) end
  end)
end
arm()

-- Observability console over the relay (cesh dial <pid>): status, view dump.
admin.attach(stat, view, function() return me end)

-- Dashboard contract: live stats, the config the editor seeds, live retune.
if ces.extension_admin then
  ces.extension_admin{
    status = function()
      return {
        peers      = tostring(stat.peers),
        core       = tostring(stat.core),
        group_size = tostring(opts.group_size),
        adds       = tostring(stat.adds),
        culls      = tostring(stat.culls),
        last       = stat.last,
        ticks      = tostring(stat.ticks),
      }
    end,
    config_defaults =
      "group_size = 20\n" ..   -- clique size the clusterer closes around the host
      "max_peers = 80\n" ..    -- 20-slot buffer under the fixed server 100 limit
      "tick_ms = 5000\n" ..    -- gossip + one move per tick
      "gossip_cap = 64\n" ..   -- peers advertised per gossip frame
      "peer_credit_target = 500000000\n" ..  -- 5 full credits lifetime PoW to count
      "dud_timeout_ms = 86400000\n",         -- 24h settle before reclaiming own duds
    on_config = function(c)
      local prev = opts.tick_ms
      opts = build_opts(c)
      if opts.tick_ms ~= prev then arm() end
    end,
  }
end

ces.log("peerclusterer: up, group_size=" .. opts.group_size ..
  " max_peers=" .. opts.max_peers .. " tick=" .. opts.tick_ms .. "ms")
ces.run()

end

__mods["clusterer"] = function()
-- clusterer - the stateless decision rule for peer clustering. PURE: given the
-- node's own pubkey, its current peer set, and a 2-hop view of who-peers-whom
-- (gossiped by peers as "these are my peers"), return ONE move toward closing a
-- clique of `group_size` around the node, or idle. No global agreement, no
-- cluster identity, no votes: a stigmergic local rule (the lineage is ant/boid
-- swarm optimization) whose fixpoint is a closed clique. ADD-ONLY: the only
-- action is to add a peer; the rule never removes (committed reserves stay).
--
-- The "pheromone" is each node periodically telling its peers its own peer list.
-- The move is triadic closure: add the not-yet-peer that the most of my current
-- peers already link to, which both densifies my neighborhood toward a clique
-- and keeps me inside my own cluster (distant nodes share no neighbors with me,
-- so distinct clusters stay distinct). The same function ships and simulates.

local M = {}

-- view: pubkey -> array of that node's peer pubkeys (its gossiped list).
-- A node's neighbor set, as a lookup table.
local function nbr_set(view, k)
  local s = {}
  local l = view[k]
  if l then for _, p in ipairs(l) do s[p] = true end end
  return s
end

-- The node's dense core: itself plus the peers densely connected to the rest of
-- the peer set (linked, per the view, to at least half the other peers). A cheap
-- clique approximation, enough to detect "my clique has closed". Returns the
-- core as a set including `me`, and its size.
local function dense_core(me, peers, view)
  local core = { [me] = true }
  local n = 1
  local np = #peers
  for _, p in ipairs(peers) do
    local pn = nbr_set(view, p)
    local links = 0
    for _, q in ipairs(peers) do
      if q ~= p and pn[q] then links = links + 1 end
    end
    -- Always include when the peer set is tiny (each peer is a cluster seed);
    -- otherwise require density (linked to >= half the other peers).
    if np <= 2 or links * 2 >= (np - 1) then
      core[p] = true
      n = n + 1
    end
  end
  return core, n
end

-- Is `core` a closed clique in the view? me links every core member by
-- construction (they are its peers); every other pair must link in the view.
-- Missing knowledge counts as not-closed (keep nudging until the view fills in).
local function is_closed(core, view, me)
  for a in pairs(core) do
    if a ~= me then
      local an = nbr_set(view, a)
      for b in pairs(core) do
        if b ~= a and b ~= me and not an[b] then return false end
      end
    end
  end
  return true
end

-- Best triadic candidate: a node that is NOT already one of my peers (exclude
-- the full peer set, not just speakers -- a peer I added but have not yet heard
-- back from is still a peer and must never be re-added), that the most of my
-- speaker-peers already link to, AND that a heard speaker vouches is itself a
-- speaker. Only speakers are recruited. Returns target, score. Deterministic
-- tie-break (lexicographically smallest pubkey) so the choice is reproducible.
local function best_candidate(me, all_peers, speaker_peers, view, vouched, culled)
  local is_peer = { [me] = true }
  for _, p in ipairs(all_peers) do is_peer[p] = true end
  local score = {}
  for _, p in ipairs(speaker_peers) do
    local l = view[p]
    if l then
      for _, q in ipairs(l) do
        if not is_peer[q] and vouched[q] and not culled[q] then
          score[q] = (score[q] or 0) + 1
        end
      end
    end
  end
  local best, best_s = nil, 0
  for q, s in pairs(score) do
    if s > best_s or (s == best_s and best and q < best) then
      best, best_s = q, s
    end
  end
  return best, best_s
end

-- decide(me, peers, view, heard, vouched, culled, opts) -> move
--   move.action = "add"  : add move.target as a peer (one move per tick)
--   move.action = "idle" : nothing to do (move.reason explains why)
-- heard   : set pubkey->true of my DIRECT peers I have received a peerclusterer
--           pheromone from. Only these count toward closing a cluster -- a peer
--           that is merely connected but silent never counts.
-- vouched : set pubkey->true of non-peer nodes a heard speaker flagged as
--           speakers. Candidate eligibility -- never recruit a non-speaker.
-- culled  : set pubkey->true of nodes the clusterer added and later reclaimed as
--           duds. Never re-recruit and never count them.
-- opts.group_size : clique size to close around me (default 20)
-- opts.max_peers  : hard headroom cap; never add beyond it (0 = no cap)
function M.decide(me, peers, view, heard, vouched, culled, opts)
  opts = opts or {}
  heard = heard or {}
  vouched = vouched or {}
  culled = culled or {}
  local group_size = opts.group_size or 20
  local max_peers  = opts.max_peers or 0

  -- speaker_peers: peers confirmed to speak peerclusterer (the cluster is built
  -- only from these). pointed: cluster-relevant peers I have already pointed at
  -- -- confirmed speakers PLUS pending vouched adds whose link has not come up
  -- yet. The cluster's actual SYNC is the C++ peer maintenance's job over time;
  -- the clusterer only points, so it must count what it has pointed at, not only
  -- what is already live.
  local speaker_peers = {}
  local pointed = 0
  for _, p in ipairs(peers) do
    if heard[p] then speaker_peers[#speaker_peers + 1] = p end
    if (heard[p] or vouched[p]) and not culled[p] then pointed = pointed + 1 end
  end

  local core, core_n = dense_core(me, speaker_peers, view)
  -- Goal: a closed clique of at least group_size speakers including me.
  if core_n >= group_size and is_closed(core, view, me) then
    return { action = "idle", reason = "closed", size = core_n }
  end
  -- Headroom guard: add-only must respect the peer-table cap. Out of headroom is
  -- the convergence-safe fallback -- idle, never evict.
  if max_peers > 0 and #peers >= max_peers then
    return { action = "idle", reason = "cap", size = core_n }
  end
  -- Don't over-point: once group_size-1 cluster-relevant peers are pointed at,
  -- stop and let the peer maintenance bring the links up. Adding more while
  -- waiting would just pile on excess peers (linking lags pointing).
  if pointed >= group_size - 1 then
    return { action = "idle", reason = "pending", size = core_n }
  end
  -- Grow toward the clique: add the strongest triadic speaker candidate. None
  -- sharing a neighbor with me => sparse view, wait for more signal (never add
  -- blind, never add a non-speaker).
  local q, s = best_candidate(me, peers, speaker_peers, view, vouched, culled)
  if q and s >= 1 then
    return { action = "add", target = q, score = s, size = core_n }
  end
  return { action = "idle", reason = "no-candidate", size = core_n }
end

-- find_duds(peers, heard, pow, added_at, now_ms, timeout_ms, pow_target) -> list
-- The peers the clusterer ADDED that, after the settle window, are not real
-- cluster members and so should be reclaimed. A peer is FULFILLED when it is
-- reciprocating RECENTLY (heard within the window) AND has reciprocated at least
-- `pow_target` lifetime inbound PoW (economically committed, not just connected).
-- A dud is one of MY adds, still a current peer, past the settle window, and not
-- fulfilled -- which catches BOTH a peer that never came alive and one that was a
-- member then went silent for the window. Reclaiming destroys no value: a peering
-- that is dead or sub-target never holds a meaningful live reserve.
--   peers     : array of my current peer pubkeys
--   heard     : pubkey -> last-heard ms timestamp (or nil if never heard)
--   pow       : pubkey -> lifetime inbound PoW (raw units)
--   added_at  : pubkey -> ms timestamp when I added it
function M.find_duds(peers, heard, pow, added_at, now_ms, timeout_ms, pow_target)
  heard = heard or {}
  pow = pow or {}
  local is_peer = {}
  for _, p in ipairs(peers) do is_peer[p] = true end
  local duds = {}
  for p, t in pairs(added_at) do
    if is_peer[p] and (now_ms - t) >= timeout_ms then
      local h = heard[p]
      local fulfilled = h and (now_ms - h) < timeout_ms
                          and (pow[p] or 0) >= pow_target
      if not fulfilled then duds[#duds + 1] = p end
    end
  end
  return duds
end

-- Exposed for tests.
M._dense_core = dense_core
M._is_closed = is_closed
M._best_candidate = best_candidate

return M

end

__mods["admin"] = function()
-- admin - observability console for the peerclusterer extension, served over the
-- /ces/lua/1 relay (cesh dial <pid>). Read-only: it answers operator/test
-- queries and never dials out, so it is not a mesh. Verbs: status, view.

local M = {}
local Admin = {}
Admin.__index = Admin

local function hex(s)
  local t = {}
  for i = 1, #s do t[i] = string.format("%02x", s:byte(i)) end
  return table.concat(t)
end

function M.new(stat, view, me_fn)
  return setmetatable({ stat = stat, view = view, me_fn = me_fn, buf = {} },
                      Admin)
end

function Admin:cmd(conn, line)
  local c = line:match("^(%S+)")
  if c == "status" then
    local s = self.stat
    conn:write(string.format(
      "peers=%d core=%d adds=%d culls=%d ticks=%d last=%s\n",
      s.peers, s.core, s.adds, s.culls, s.ticks, s.last))
  elseif c == "view" then
    local me = self.me_fn and self.me_fn() or nil
    for k, peers in pairs(self.view) do
      local tag = (k == me) and "*" or " "
      conn:write(tag .. hex(k):sub(1, 16) .. " n=" .. #peers .. "\n")
    end
    conn:write("END\n")
  else
    conn:write("ERR unknown\n")
  end
end

function Admin:on_data(conn, data)
  local b = (self.buf[conn.id] or "") .. data
  while true do
    local line, rest = b:match("^(.-)\n(.*)$")
    if not line then break end
    b = rest
    self:cmd(conn, line)
  end
  self.buf[conn.id] = b
end

function Admin:on_close(conn) self.buf[conn.id] = nil end

function M.attach(stat, view, me_fn)
  local a = M.new(stat, view, me_fn)
  ces.conn.set_listener({
    on_data  = function(conn, data) a:on_data(conn, data) end,
    on_close = function(conn) a:on_close(conn) end,
  })
  return a
end

return M

end

__mods["conf"] = function()
-- conf - load an operator-deployed config file for an L2 extension from the file
-- store. Format: "key = value" lines; "#" starts a comment; blank and malformed
-- lines are ignored. load() returns a string->string table ({} if the file is
-- absent or file ops are unavailable, so a program always has working defaults);
-- num() and list() coerce a value. The same extension reads the same path in
-- production and under test; only the deployed file differs.

local M = {}

function M.load(path)
  local out = {}
  if not ces.file_read or not ces.file_stat then return out end
  -- READ rejects a range past EOF, so size the read to the file (stat first).
  local st = ces.file_stat(path)
  if not st or not st.size or st.size == 0 then return out end
  local n = st.size < 65536 and st.size or 65536
  local data = ces.file_read(path, 0, n)
  if not data or data == "" then return out end
  for line in (data .. "\n"):gmatch("(.-)\n") do
    local s = line:gsub("#.*$", "")
    local k, v = s:match("^%s*([%w_]+)%s*=%s*(.-)%s*$")
    if k then out[k] = v end
  end
  return out
end

-- Numeric value of key k, or default.
function M.num(t, k, default)
  local n = t[k] and tonumber(t[k])
  return n or default
end

-- Comma-separated value of key k as a list of trimmed, non-empty strings ({}).
function M.list(t, k)
  local out = {}
  if t[k] then
    for item in (t[k] .. ","):gmatch("%s*([^,]-)%s*,") do
      if item ~= "" then out[#out + 1] = item end
    end
  end
  return out
end

return M

end

CES_MANIFEST = { name = "Peer Clusterer", version = "0.1", description = "Stigmergic peering agent: nudges the host's peer table into closed cliques (clusters) of a target size by gossiping peer lists and adding the best triadic-closure edge each tick. Add-only, no consensus, no votes." }
return require("main")
