-- generated by cesdk 0.1.0, do not edit
-- project: walkabout 0.1.0

local __mods, __cache = {}, {}
local function require(name)
  local c = __cache[name]
  if c ~= nil then return c end
  local f = __mods[name]
  if not f then error("cesdk bundle: module '" .. name .. "' not found", 2) end
  local r = f()
  if r == nil then r = true end
  __cache[name] = r
  return r
end

__mods["cesdk.manifest"] = function() return { name = "walkabout", version = "0.1.0", protocols = {  } } end

__mods["main"] = function()
-- walkabout - a tiny real-time multiplayer world served through cesweb.
--
-- One compute instance serves BOTH halves over ces.conn (the cesweb /i/ scope):
--   HTTP GET  -> the HTML5/JS client page (web.on_request)
--   WebSocket -> the live game (web.on_websocket)
-- No client download: open the /i/ URL in two browser windows and walk about.

local web  = require("web")
local game = require("game")
local page = require("page")

web.serve{
  on_request   = function(_req) return web.html(page.HTML) end,
  on_websocket = function(ws) game.on_connect(ws) end,
}

web.run()

end

__mods["web"] = function()
-- web.lua - HTTP/1.1 + WebSocket server machinery over ces.conn.
--
-- Rides the cesweb /i/ proxy. cesweb is the browser's TLS peer, so it terminates
-- the wire protocol and hands a compute program one of two shapes on a ces.conn:
--
--   HTTP  : raw request bytes ("GET / HTTP/1.1\r\n...\r\n\r\n"); answer once with
--           an HTTP response, then close (Connection: close).
--   WebSocket : length-framed messages, [u32 BE len][payload]. Frame 0 is the
--           handshake request (so the program can route by path / read cookies);
--           frames 1..N are message payloads. A payload sent back is delivered to
--           the browser as one text WebSocket message.
--
-- The two are told apart by the first byte of the first chunk: an HTTP method is
-- an uppercase ASCII letter (>= 0x41); a frame length's high byte is 0x00
-- (messages are far under 16 MiB). So byte0 == 0 => WebSocket, else => HTTP.
--
-- Usage:
--   local web = require("web")
--   web.serve{
--     on_request   = function(req) return web.html("<h1>hi</h1>") end,
--     on_websocket = function(ws)
--       ws.on_message = function(msg) ws.send("you said: "..msg) end
--     end,
--   }
--   web.run()   -- = ces.run()
--
--   req = { method, target, path, query, headers = {lowercased->value}, body }
--   ws  = { id, path, query, headers, send(msg), close(), on_message, on_close }

local M = {}

-- u32 big-endian pack/unpack via arithmetic (doubles are exact to 2^53).
local function u32be(n)
  return string.char(math.floor(n / 16777216) % 256,
                     math.floor(n / 65536) % 256,
                     math.floor(n / 256) % 256,
                     n % 256)
end
local function rd_u32be(s, i)          -- i = 1-based index of the length's first byte
  local a, b, c, d = s:byte(i, i + 3)
  return ((a * 256 + b) * 256 + c) * 256 + d
end

-- Parse an HTTP request (or the WebSocket handshake request in frame 0).
local function parse_request(raw)
  local head = raw:match("^(.-)\r\n\r\n")
  if not head then return nil end
  local body = raw:sub(#head + 5)
  local first = head:match("^(.-)\r\n") or head
  local method, target = first:match("^(%S+)%s+(%S+)")
  if not method then return nil end
  local path, query = target:match("^([^?]*)%??(.*)$")
  local headers = {}
  for line in head:gmatch("\r\n([^\r\n]+)") do
    local k, v = line:match("^([^:]+):%s*(.*)$")
    if k then headers[k:lower()] = v end
  end
  return { method = method, target = target, path = path, query = query,
           headers = headers, body = body }
end

local REASON = { [200] = "OK", [400] = "Bad Request", [404] = "Not Found",
                 [500] = "Internal Server Error" }

-- Build an HTTP/1.1 response from a string or a { status, headers, body } table.
local function build_response(resp)
  if type(resp) == "string" then resp = { body = resp } end
  resp = resp or { status = 404 }
  local status = resp.status or 200
  local reason = resp.reason or REASON[status] or ""
  local body = resp.body or ""
  local out = { ("HTTP/1.1 %d %s\r\n"):format(status, reason) }
  local have_ct = false
  if resp.headers then
    for k, v in pairs(resp.headers) do
      if k:lower() == "content-type" then have_ct = true end
      out[#out + 1] = k .. ": " .. tostring(v) .. "\r\n"
    end
  end
  if not have_ct then out[#out + 1] = "Content-Type: text/html; charset=utf-8\r\n" end
  out[#out + 1] = "Content-Length: " .. #body .. "\r\n"
  out[#out + 1] = "Connection: close\r\n\r\n"
  out[#out + 1] = body
  return table.concat(out)
end

-- Response helpers.
function M.html(body, status)
  return { status = status or 200, body = body or "",
           headers = { ["Content-Type"] = "text/html; charset=utf-8" } }
end
function M.text(body, status)
  return { status = status or 200, body = body or "",
           headers = { ["Content-Type"] = "text/plain; charset=utf-8" } }
end
function M.response(status, body, headers)
  return { status = status, body = body, headers = headers }
end

local function make_ws(conn, hs)
  local ws = {
    id = conn.id,
    path = hs and hs.path or "/",
    query = hs and hs.query or "",
    headers = hs and hs.headers or {},
    on_message = nil,
    on_close = nil,
  }
  function ws.send(msg)
    msg = tostring(msg)
    return conn:write(u32be(#msg) .. msg)
  end
  function ws.close() conn:close() end
  return ws
end

-- serve{ on_request, on_websocket }: arm the ces.conn listener and dispatch.
function M.serve(opts)
  opts = opts or {}
  local on_request = opts.on_request
  local on_websocket = opts.on_websocket
  local conns = {}                        -- conn.id -> per-connection state

  local function handle_http(st, conn)
    if not st.buf:find("\r\n\r\n", 1, true) then return end   -- headers incomplete
    local req = parse_request(st.buf)
    if not req then
      st.done = true
      conn:write(build_response(M.response(400, "bad request")))
      conn:close()
      return
    end
    -- Wait for the full request body (POST/PUT/...) before dispatching.
    local clen = tonumber(req.headers["content-length"]) or 0
    if #req.body < clen then return end
    st.done = true
    local resp
    if on_request then
      local ok, r = pcall(on_request, req)
      resp = ok and r or M.response(500, "internal error")
    end
    conn:write(build_response(resp))
    conn:close()
  end

  local function handle_ws(st, conn)
    while true do
      if #st.buf < 4 then return end
      local len = rd_u32be(st.buf, 1)
      if #st.buf < 4 + len then return end
      local payload = st.buf:sub(5, 4 + len)
      st.buf = st.buf:sub(5 + len)
      if not st.ws then
        local ws = make_ws(conn, parse_request(payload))   -- frame 0 = handshake
        st.ws = ws
        if on_websocket then pcall(on_websocket, ws) end
      elseif st.ws.on_message then
        pcall(st.ws.on_message, payload)
      end
    end
  end

  ces.conn.set_listener{
    on_open = function(conn) conns[conn.id] = { buf = "" } end,
    on_data = function(conn, data)
      local st = conns[conn.id]
      if not st then st = { buf = "" }; conns[conn.id] = st end
      if st.done then return end
      st.buf = st.buf .. data
      if not st.mode then
        local b0 = st.buf:byte(1)
        if b0 == nil then return end
        st.mode = (b0 == 0) and "ws" or "http"
      end
      if st.mode == "http" then handle_http(st, conn) else handle_ws(st, conn) end
    end,
    on_close = function(conn)
      local st = conns[conn.id]
      if st and st.ws and st.ws.on_close then pcall(st.ws.on_close) end
      conns[conn.id] = nil
    end,
  }
end

function M.run() return ces.run() end

return M

end

__mods["game"] = function()
-- game.lua - walkabout world state. Space-delimited text protocol (no JSON dep):
--
--   server -> client :  welcome <id> <w> <h> <name> <x> <y>
--                       join <id> <name> <x> <y>
--                       pos <id> <x> <y>
--                       leave <id>
--   client -> server :  move <x> <y>
--
-- ids are strings (conn.id stringified). One connection == one avatar.

local M = {}

local WORLD_W, WORLD_H = 640, 480
local NAMES = { "Ada", "Grace", "Alan", "Linus", "Edsger", "Barbara", "Ken",
                "Dennis", "Rob", "Margaret", "Tim", "Radia", "Vint", "Hedy",
                "Katherine", "Donald", "Leslie", "Frances", "John", "Karen" }

local players = {}   -- id(string) -> { ws, name, x, y }

-- Uniform-ish integer in [0, n-1] from CES randomness (no os seed to trust).
local function rnd(n)
  local b = ces.random_bytes(4)
  local v = ((b:byte(1) * 256 + b:byte(2)) * 256 + b:byte(3)) * 256 + b:byte(4)
  return v % n
end

local function rand_name() return NAMES[rnd(#NAMES) + 1] .. tostring(10 + rnd(90)) end

local function clampi(v, lo, hi)
  v = math.floor(tonumber(v) or lo)
  if v < lo then return lo elseif v > hi then return hi end
  return v
end

local function send_all(msg, except)
  for id, p in pairs(players) do
    if id ~= except then p.ws.send(msg) end
  end
end

function M.on_connect(ws)
  local id = tostring(ws.id)
  local p = { ws = ws, name = rand_name(),
              x = 20 + rnd(WORLD_W - 40), y = 20 + rnd(WORLD_H - 40) }
  players[id] = p

  ws.send("welcome " .. id .. " " .. WORLD_W .. " " .. WORLD_H ..
          " " .. p.name .. " " .. p.x .. " " .. p.y)
  for oid, q in pairs(players) do
    if oid ~= id then
      ws.send("join " .. oid .. " " .. q.name .. " " .. q.x .. " " .. q.y)
    end
  end
  send_all("join " .. id .. " " .. p.name .. " " .. p.x .. " " .. p.y, id)

  ws.on_message = function(msg)
    local cmd, a, b = msg:match("^(%S+)%s+(%S+)%s+(%S+)")
    if cmd == "move" then
      local pp = players[id]
      if not pp then return end
      pp.x = clampi(a, 0, WORLD_W)
      pp.y = clampi(b, 0, WORLD_H)
      send_all("pos " .. id .. " " .. pp.x .. " " .. pp.y, nil)
    end
  end

  ws.on_close = function()
    players[id] = nil
    send_all("leave " .. id, nil)
  end
end

return M

end

__mods["page"] = function()
-- page.lua - the HTML5/JS client, served verbatim over HTTP. It opens a
-- WebSocket back to the SAME /i/ instance (its own path + "/ws"), so one URL in
-- two browser windows is two avatars. Plain canvas; no build step, no framework.

local M = {}

M.HTML = [==[<!doctype html>
<html lang=en><meta charset=utf-8>
<meta name=viewport content="width=device-width,initial-scale=1">
<title>walkabout</title>
<style>
  :root{color-scheme:dark}
  html,body{margin:0;height:100%;background:#0f1116;color:#e7e9ee;
    font:15px/1.5 system-ui,sans-serif}
  #wrap{display:flex;flex-direction:column;align-items:center;gap:.6rem;padding:1rem}
  h1{font-size:1.1rem;margin:.2rem 0;font-weight:600;letter-spacing:.02em}
  #hud{color:#9aa2b1;font-size:.9rem;min-height:1.2em}
  #hud b{color:#e7e9ee}
  canvas{background:#171a22;border:1px solid #2a2f3a;border-radius:10px;
    box-shadow:0 10px 40px #0008;touch-action:none}
  #tip{color:#6a7282;font-size:.82rem}
  code{background:#ffffff12;padding:.05em .35em;border-radius:4px}
</style>
<div id=wrap>
  <h1>walkabout</h1>
  <div id=hud>connecting...</div>
  <canvas id=c width=640 height=480></canvas>
  <div id=tip>move with <code>WASD</code> or the arrow keys</div>
</div>
<script>
const cv = document.getElementById('c'), ctx = cv.getContext('2d');
const hud = document.getElementById('hud');
let meId = null, W = 640, H = 480;
const players = new Map();            // id -> {name,x,y}

function hue(id){ let h=0; for(const ch of id) h=(h*31+ch.charCodeAt(0))>>>0; return h%360; }

function draw(){
  ctx.clearRect(0,0,cv.width,cv.height);
  ctx.strokeStyle='#2a2f3a'; ctx.strokeRect(.5,.5,cv.width-1,cv.height-1);
  for(const [id,p] of players){
    const me = id===meId, c = `hsl(${hue(id)} 70% ${me?62:55}%)`;
    ctx.beginPath(); ctx.arc(p.x,p.y,me?11:9,0,7); ctx.fillStyle=c; ctx.fill();
    if(me){ ctx.lineWidth=2; ctx.strokeStyle='#fff'; ctx.stroke(); }
    ctx.fillStyle='#c9cedb'; ctx.font='12px system-ui'; ctx.textAlign='center';
    ctx.fillText(p.name,p.x,p.y-15);
  }
  hud.innerHTML = meId
    ? `you are <b>${(players.get(meId)||{}).name||'?'}</b> &middot; ${players.size} here`
    : 'connecting...';
}

const wsUrl = (location.protocol==='https:'?'wss':'ws')+'://'+location.host+
  location.pathname.replace(/\/+$/,'')+'/ws';
let ws, dead=false;
function connect(){
  ws = new WebSocket(wsUrl);
  ws.onmessage = e => {
    const a = String(e.data).split(' '), t = a[0];
    if(t==='welcome'){ players.clear(); meId=a[1]; W=+a[2]; H=+a[3];
      players.set(meId,{name:a[4],x:+a[5],y:+a[6]}); }
    else if(t==='join'){ players.set(a[1],{name:a[2],x:+a[3],y:+a[4]}); }
    else if(t==='pos'){ const p=players.get(a[1]); if(p){p.x=+a[2];p.y=+a[3];} }
    else if(t==='leave'){ players.delete(a[1]); }
    draw();
  };
  ws.onclose = () => { hud.textContent='disconnected'; if(!dead) setTimeout(connect,1500); };
  ws.onerror = () => ws.close();
}
connect();
window.addEventListener('beforeunload',()=>{dead=true;});

// held-keys movement, integrated in a loop, sent throttled.
const keys = {};
const KEY = {ArrowUp:'u',KeyW:'u',ArrowDown:'d',KeyS:'d',ArrowLeft:'l',KeyA:'l',ArrowRight:'r',KeyD:'r'};
addEventListener('keydown',e=>{ const k=KEY[e.code]; if(k){keys[k]=1; e.preventDefault();} });
addEventListener('keyup',  e=>{ const k=KEY[e.code]; if(k){keys[k]=0;} });

let last=performance.now(), lastSent=0;
function loop(now){
  const dt=Math.min(.05,(now-last)/1000); last=now;
  const me = meId && players.get(meId);
  if(me){
    const sp=170*dt; let dx=0,dy=0;
    if(keys.l)dx--; if(keys.r)dx++; if(keys.u)dy--; if(keys.d)dy++;
    if(dx||dy){
      me.x=Math.max(0,Math.min(W,me.x+dx*sp));
      me.y=Math.max(0,Math.min(H,me.y+dy*sp));
      if(ws&&ws.readyState===1&&now-lastSent>45){
        ws.send('move '+Math.round(me.x)+' '+Math.round(me.y)); lastSent=now;
      }
      draw();
    }
  }
  requestAnimationFrame(loop);
}
requestAnimationFrame(loop);
</script>
]==]

return M

end

CES_MANIFEST = { name = "walkabout", version = "0.1.0", description = "" }
return require("main")
